# rose-pine-dawn hypr/hyprlock colors.
$rosewater = rgb(575279)
$rosewaterAlpha = 575279
$flamingo = rgb(575279)
$flamingoAlpha = 575279
$pink = rgb(907aa9)
$pinkAlpha = 907aa9
$mauve = rgb(907aa9)
$mauveAlpha = 907aa9
$red = rgb(b4637a)
$redAlpha = b4637a
$maroon = rgb(b4637a)
$maroonAlpha = b4637a
$peach = rgb(ea9d34)
$peachAlpha = ea9d34
$yellow = rgb(ea9d34)
$yellowAlpha = ea9d34
$green = rgb(286983)
$greenAlpha = 286983
$teal = rgb(d7827e)
$tealAlpha = d7827e
$sky = rgb(d7827e)
$skyAlpha = d7827e
$sapphire = rgb(56949f)
$sapphireAlpha = 56949f
$blue = rgb(56949f)
$blueAlpha = 56949f
$lavender = rgb(56949f)
$lavenderAlpha = 56949f
$text = rgb(575279)
$textAlpha = 575279
$subtext1 = rgb(575279)
$subtext1Alpha = 575279
$subtext0 = rgb(575279)
$subtext0Alpha = 575279
$overlay2 = rgb(9893a5)
$overlay2Alpha = 9893a5
$overlay1 = rgb(9893a5)
$overlay1Alpha = 9893a5
$overlay0 = rgb(9893a5)
$overlay0Alpha = 9893a5
$surface2 = rgb(9893a5)
$surface2Alpha = 9893a5
$surface1 = rgb(f2e9e1)
$surface1Alpha = f2e9e1
$surface0 = rgb(f2e9e1)
$surface0Alpha = f2e9e1
$base = rgb(faf4ed)
$baseAlpha = faf4ed
$mantle = rgb(faf4ed)
$mantleAlpha = faf4ed
$crust = rgb(faf4ed)
$crustAlpha = faf4ed

$active_border = rgba(907aa9ee) rgba(56949fee) 45deg
$inactive_border = rgba(9893a5aa)
$shadow_color = rgba(faf4edee)
