# ayu-light tmux colors
set -g pane-border-style fg=#8a9199
set -g pane-active-border-style fg=#a37acc
set -g status-bg '#e6e1cf'
set -g status-fg '#5c6166'
set -g status-left '#[fg=#4cbf99]#S #[fg=#f2ae49]|'
set -g status-right '#[fg=#4cbf99]%Y-%m-%d #[fg=#5c6166]%H:%M #[fg=#f07171][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#5c6166,bold]#I:#W#[default]'
