# catppuccin-latte hypr/hyprlock colors.
$rosewater = rgb(acb0be)
$rosewaterAlpha = acb0be
$flamingo = rgb(acb0be)
$flamingoAlpha = acb0be
$pink = rgb(ea76cb)
$pinkAlpha = ea76cb
$mauve = rgb(ea76cb)
$mauveAlpha = ea76cb
$red = rgb(d20f39)
$redAlpha = d20f39
$maroon = rgb(d20f39)
$maroonAlpha = d20f39
$peach = rgb(df8e1d)
$peachAlpha = df8e1d
$yellow = rgb(df8e1d)
$yellowAlpha = df8e1d
$green = rgb(40a02b)
$greenAlpha = 40a02b
$teal = rgb(179299)
$tealAlpha = 179299
$sky = rgb(179299)
$skyAlpha = 179299
$sapphire = rgb(1e66f5)
$sapphireAlpha = 1e66f5
$blue = rgb(1e66f5)
$blueAlpha = 1e66f5
$lavender = rgb(1e66f5)
$lavenderAlpha = 1e66f5
$text = rgb(4c4f69)
$textAlpha = 4c4f69
$subtext1 = rgb(acb0be)
$subtext1Alpha = acb0be
$subtext0 = rgb(acb0be)
$subtext0Alpha = acb0be
$overlay2 = rgb(6c6f85)
$overlay2Alpha = 6c6f85
$overlay1 = rgb(6c6f85)
$overlay1Alpha = 6c6f85
$overlay0 = rgb(6c6f85)
$overlay0Alpha = 6c6f85
$surface2 = rgb(6c6f85)
$surface2Alpha = 6c6f85
$surface1 = rgb(5c5f77)
$surface1Alpha = 5c5f77
$surface0 = rgb(5c5f77)
$surface0Alpha = 5c5f77
$base = rgb(eff1f5)
$baseAlpha = eff1f5
$mantle = rgb(eff1f5)
$mantleAlpha = eff1f5
$crust = rgb(eff1f5)
$crustAlpha = eff1f5

$active_border = rgba(ea76cbee) rgba(1e66f5ee) 45deg
$inactive_border = rgba(6c6f85aa)
$shadow_color = rgba(eff1f5ee)
