# dracula tmux colors
set -g pane-border-style fg=#6272a4
set -g pane-active-border-style fg=#ff79c6
set -g status-bg '#282a36'
set -g status-fg '#f8f8f2'
set -g status-left '#[fg=#8be9fd]#S #[fg=#f1fa8c]|'
set -g status-right '#[fg=#8be9fd]%Y-%m-%d #[fg=#f8f8f2]%H:%M #[fg=#f1fa8c][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#f8f8f2,bold]#I:#W#[default]'
