# catppuccin-mocha tmux colors
set -g pane-border-style fg=#585b70
set -g pane-active-border-style fg=#f5c2e7
set -g status-bg '#1e1e2e'
set -g status-fg '#cdd6f4'
set -g status-left '#[fg=#94e2d5]#S #[fg=#f9e2af]|'
set -g status-right '#[fg=#94e2d5]%Y-%m-%d #[fg=#cdd6f4]%H:%M #[fg=#f9e2af][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#bac2de,bold]#I:#W#[default]'
