# rose-pine hypr/hyprlock colors.
$rosewater = rgb(e0def4)
$rosewaterAlpha = e0def4
$flamingo = rgb(e0def4)
$flamingoAlpha = e0def4
$pink = rgb(c4a7e7)
$pinkAlpha = c4a7e7
$mauve = rgb(c4a7e7)
$mauveAlpha = c4a7e7
$red = rgb(eb6f92)
$redAlpha = eb6f92
$maroon = rgb(eb6f92)
$maroonAlpha = eb6f92
$peach = rgb(f6c177)
$peachAlpha = f6c177
$yellow = rgb(f6c177)
$yellowAlpha = f6c177
$green = rgb(31748f)
$greenAlpha = 31748f
$teal = rgb(ebbcba)
$tealAlpha = ebbcba
$sky = rgb(ebbcba)
$skyAlpha = ebbcba
$sapphire = rgb(9ccfd8)
$sapphireAlpha = 9ccfd8
$blue = rgb(9ccfd8)
$blueAlpha = 9ccfd8
$lavender = rgb(9ccfd8)
$lavenderAlpha = 9ccfd8
$text = rgb(e0def4)
$textAlpha = e0def4
$subtext1 = rgb(e0def4)
$subtext1Alpha = e0def4
$subtext0 = rgb(e0def4)
$subtext0Alpha = e0def4
$overlay2 = rgb(6e6a86)
$overlay2Alpha = 6e6a86
$overlay1 = rgb(6e6a86)
$overlay1Alpha = 6e6a86
$overlay0 = rgb(6e6a86)
$overlay0Alpha = 6e6a86
$surface2 = rgb(6e6a86)
$surface2Alpha = 6e6a86
$surface1 = rgb(26233a)
$surface1Alpha = 26233a
$surface0 = rgb(26233a)
$surface0Alpha = 26233a
$base = rgb(191724)
$baseAlpha = 191724
$mantle = rgb(191724)
$mantleAlpha = 191724
$crust = rgb(191724)
$crustAlpha = 191724

$active_border = rgba(c4a7e7ee) rgba(9ccfd8ee) 45deg
$inactive_border = rgba(6e6a86aa)
$shadow_color = rgba(191724ee)
