FROM opensuse/leap:15.5

# Install essential packages
RUN zypper refresh && zypper install -y \
    curl \
    git \
    sudo \
    wget \
    gcc \
    gcc-c++ \
    make \
    stow \
    ca-certificates \
    && zypper clean -a

# Create test user with sudo privileges
RUN useradd -m -s /bin/bash testuser && \
    echo 'testuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install BATS testing framework
RUN git clone https://github.com/bats-core/bats-core.git /tmp/bats-core && \
    cd /tmp/bats-core && \
    ./install.sh /usr/local && \
    rm -rf /tmp/bats-core

# Install BATS helper libraries
RUN git clone https://github.com/bats-core/bats-support.git /usr/local/lib/bats-support && \
    git clone https://github.com/bats-core/bats-assert.git /usr/local/lib/bats-assert && \
    git clone https://github.com/bats-core/bats-file.git /usr/local/lib/bats-file

# Set working directory
WORKDIR /dotfiles

# Switch to test user
USER testuser

# Set up environment
ENV HOME=/home/testuser
ENV PATH=$PATH:/home/testuser/.local/bin

CMD ["/bin/bash"]