# ayu-light kitty colors.
foreground              #5c6166
background              #fcfcfc
selection_foreground    #5c6166
selection_background    #8a9199
url_color               #399ee6
color0  #e6e1cf
color1  #f07171
color2  #86b300
color3  #f2ae49
color4  #399ee6
color5  #a37acc
color6  #4cbf99
color7  #5c6166
color8  #8a9199
color9  #f07171
color10 #86b300
color11 #f2ae49
color12 #399ee6
color13 #a37acc
color14 #4cbf99
color15 #5c6166
cursor                  #5c6166
cursor_text_color       #fcfcfc
active_border_color     #a37acc
inactive_border_color   #8a9199
