# material hypr/hyprlock colors.
$rosewater = rgb(eeffff)
$rosewaterAlpha = eeffff
$flamingo = rgb(eeffff)
$flamingoAlpha = eeffff
$pink = rgb(c792ea)
$pinkAlpha = c792ea
$mauve = rgb(c792ea)
$mauveAlpha = c792ea
$red = rgb(f07178)
$redAlpha = f07178
$maroon = rgb(f07178)
$maroonAlpha = f07178
$peach = rgb(ffcb6b)
$peachAlpha = ffcb6b
$yellow = rgb(ffcb6b)
$yellowAlpha = ffcb6b
$green = rgb(c3e88d)
$greenAlpha = c3e88d
$teal = rgb(89ddff)
$tealAlpha = 89ddff
$sky = rgb(89ddff)
$skyAlpha = 89ddff
$sapphire = rgb(82aaff)
$sapphireAlpha = 82aaff
$blue = rgb(82aaff)
$blueAlpha = 82aaff
$lavender = rgb(82aaff)
$lavenderAlpha = 82aaff
$text = rgb(eeffff)
$textAlpha = eeffff
$subtext1 = rgb(eeffff)
$subtext1Alpha = eeffff
$subtext0 = rgb(eeffff)
$subtext0Alpha = eeffff
$overlay2 = rgb(546e7a)
$overlay2Alpha = 546e7a
$overlay1 = rgb(546e7a)
$overlay1Alpha = 546e7a
$overlay0 = rgb(546e7a)
$overlay0Alpha = 546e7a
$surface2 = rgb(546e7a)
$surface2Alpha = 546e7a
$surface1 = rgb(000000)
$surface1Alpha = 000000
$surface0 = rgb(000000)
$surface0Alpha = 000000
$base = rgb(263238)
$baseAlpha = 263238
$mantle = rgb(263238)
$mantleAlpha = 263238
$crust = rgb(263238)
$crustAlpha = 263238

$active_border = rgba(c792eaee) rgba(82aaffee) 45deg
$inactive_border = rgba(546e7aaa)
$shadow_color = rgba(263238ee)
