# rose-pine tmux colors
set -g pane-border-style fg=#6e6a86
set -g pane-active-border-style fg=#31748f
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#ebbcba,fg=#191724'
set -g status-left '#[fg=#191724,bold]#S #[fg=#524f67]|'
set -g status-right '#[fg=#403d52]%Y-%m-%d #[fg=#191724,bold]%H:%M #[fg=#403d52][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#31748f,fg=#e0def4,bold] #I:#W #[default]'
