# ayu-light hypr/hyprlock colors.
$rosewater = rgb(5c6166)
$rosewaterAlpha = 5c6166
$flamingo = rgb(5c6166)
$flamingoAlpha = 5c6166
$pink = rgb(a37acc)
$pinkAlpha = a37acc
$mauve = rgb(a37acc)
$mauveAlpha = a37acc
$red = rgb(f07171)
$redAlpha = f07171
$maroon = rgb(f07171)
$maroonAlpha = f07171
$peach = rgb(f2ae49)
$peachAlpha = f2ae49
$yellow = rgb(f2ae49)
$yellowAlpha = f2ae49
$green = rgb(86b300)
$greenAlpha = 86b300
$teal = rgb(4cbf99)
$tealAlpha = 4cbf99
$sky = rgb(4cbf99)
$skyAlpha = 4cbf99
$sapphire = rgb(399ee6)
$sapphireAlpha = 399ee6
$blue = rgb(399ee6)
$blueAlpha = 399ee6
$lavender = rgb(399ee6)
$lavenderAlpha = 399ee6
$text = rgb(5c6166)
$textAlpha = 5c6166
$subtext1 = rgb(5c6166)
$subtext1Alpha = 5c6166
$subtext0 = rgb(5c6166)
$subtext0Alpha = 5c6166
$overlay2 = rgb(8a9199)
$overlay2Alpha = 8a9199
$overlay1 = rgb(8a9199)
$overlay1Alpha = 8a9199
$overlay0 = rgb(8a9199)
$overlay0Alpha = 8a9199
$surface2 = rgb(8a9199)
$surface2Alpha = 8a9199
$surface1 = rgb(e6e1cf)
$surface1Alpha = e6e1cf
$surface0 = rgb(e6e1cf)
$surface0Alpha = e6e1cf
$base = rgb(fcfcfc)
$baseAlpha = fcfcfc
$mantle = rgb(fcfcfc)
$mantleAlpha = fcfcfc
$crust = rgb(fcfcfc)
$crustAlpha = fcfcfc

$active_border = rgba(a37accee) rgba(399ee6ee) 45deg
$inactive_border = rgba(8a9199aa)
$shadow_color = rgba(fcfcfcee)
