# Gruvbox Dark - hyprland/hyprlock color variables
$rosewater = rgb(ebdbb2)
$rosewaterAlpha = ebdbb2
$flamingo = rgb(d5c4a1)
$flamingoAlpha = d5c4a1
$pink = rgb(d3869b)
$pinkAlpha = d3869b
$mauve = rgb(b16286)
$mauveAlpha = b16286
$red = rgb(cc241d)
$redAlpha = cc241d
$maroon = rgb(fb4934)
$maroonAlpha = fb4934
$peach = rgb(d65d0e)
$peachAlpha = d65d0e
$yellow = rgb(d79921)
$yellowAlpha = d79921
$green = rgb(98971a)
$greenAlpha = 98971a
$teal = rgb(689d6a)
$tealAlpha = 689d6a
$sky = rgb(8ec07c)
$skyAlpha = 8ec07c
$sapphire = rgb(83a598)
$sapphireAlpha = 83a598
$blue = rgb(458588)
$blueAlpha = 458588
$lavender = rgb(83a598)
$lavenderAlpha = 83a598
$text = rgb(ebdbb2)
$textAlpha = ebdbb2
$subtext1 = rgb(d5c4a1)
$subtext1Alpha = d5c4a1
$subtext0 = rgb(bdae93)
$subtext0Alpha = bdae93
$overlay2 = rgb(a89984)
$overlay2Alpha = a89984
$overlay1 = rgb(928374)
$overlay1Alpha = 928374
$overlay0 = rgb(7c6f64)
$overlay0Alpha = 7c6f64
$surface2 = rgb(665c54)
$surface2Alpha = 665c54
$surface1 = rgb(504945)
$surface1Alpha = 504945
$surface0 = rgb(3c3836)
$surface0Alpha = 3c3836
$base = rgb(282828)
$baseAlpha = 282828
$mantle = rgb(1d2021)
$mantleAlpha = 1d2021
$crust = rgb(141617)
$crustAlpha = 141617

$active_border = rgba(b16286ee) rgba(98971aee) 45deg
$inactive_border = rgba(665c54aa)
$shadow_color = rgba(141617ee)
