# rose-pine-moon tmux colors
set -g pane-border-style fg=#6e6a86
set -g pane-active-border-style fg=#3e8fb0
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#b6b4ca,fg=#232136'
set -g status-left '#[fg=#232136,bold]#S #[fg=#4d4143]|'
set -g status-right '#[fg=#553f4e]%Y-%m-%d #[fg=#232136,bold]%H:%M #[fg=#4d4143][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#3e8fb0,fg=#141414,bold] #I:#W #[default]'
