# palenight tmux colors
set -g pane-border-style fg=#434758
set -g pane-active-border-style fg=#a3f7ff
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#8e93b1,fg=#292d3e'
set -g status-left '#[fg=#292d3e,bold]#S #[fg=#292d3e]|'
set -g status-right '#[fg=#292d3e]%Y-%m-%d #[fg=#292d3e,bold]%H:%M #[fg=#292d3e][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#a3f7ff,fg=#292d3e,bold] #I:#W #[default]'
