# palenight tmux colors
set -g pane-border-style fg=#434758
set -g pane-active-border-style fg=#c792ea
set -g status-bg '#292d3e'
set -g status-fg '#a6accd'
set -g status-left '#[fg=#89ddff]#S #[fg=#ffcb6b]|'
set -g status-right '#[fg=#89ddff]%Y-%m-%d #[fg=#a6accd]%H:%M #[fg=#ffcb6b][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#d0d0d0,bold]#I:#W#[default]'
