# tokyonight-moon tmux colors
set -g pane-border-style fg=#444a73
set -g pane-active-border-style fg=#c099ff
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#222436,fg=#c8d3f5'
set -g status-left '#[fg=#86e1fc]#S #[fg=#ffc777]|'
set -g status-right '#[fg=#86e1fc]%Y-%m-%d #[fg=#c8d3f5]%H:%M #[fg=#ffc777][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#828bb8,bold]#I:#W#[default]'
