# melange kitty colors.
foreground              #ece1d7
background              #292522
selection_foreground    #ece1d7
selection_background    #867462
url_color               #a3a9ce
color0  #34302c
color1  #bd8183
color2  #78997a
color3  #ebc06d
color4  #a3a9ce
color5  #b380b0
color6  #87a987
color7  #c1a78e
color8  #867462
color9  #d47766
color10 #85b695
color11 #ecd28b
color12 #a3a9ce
color13 #cf9bc2
color14 #89b3b6
color15 #ece1d7
cursor                  #ece1d7
cursor_text_color       #292522
active_border_color     #b380b0
inactive_border_color   #867462
