# kanagawa-dragon tmux colors
set -g pane-border-style fg=#a6a69c
set -g pane-active-border-style fg=#a292a3
set -g status-bg '#181616'
set -g status-fg '#c5c9c5'
set -g status-left '#[fg=#8ea4a2]#S #[fg=#c4b28a]|'
set -g status-right '#[fg=#8ea4a2]%Y-%m-%d #[fg=#c5c9c5]%H:%M #[fg=#c4b28a][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#c8c093,bold]#I:#W#[default]'
