# kanagawa-dragon tmux colors
set -g pane-border-style fg=#a6a69c
set -g pane-active-border-style fg=#905854
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#9fa29f,fg=#181616'
set -g status-left '#[fg=#181616,bold]#S #[fg=#3a352d]|'
set -g status-right '#[fg=#303232]%Y-%m-%d #[fg=#181616,bold]%H:%M #[fg=#3a352d][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#905854,fg=#f0f0f0,bold] #I:#W #[default]'
