# melange hypr/hyprlock colors.
$rosewater = rgb(c1a78e)
$rosewaterAlpha = c1a78e
$flamingo = rgb(c1a78e)
$flamingoAlpha = c1a78e
$pink = rgb(cf9bc2)
$pinkAlpha = cf9bc2
$mauve = rgb(b380b0)
$mauveAlpha = b380b0
$red = rgb(bd8183)
$redAlpha = bd8183
$maroon = rgb(d47766)
$maroonAlpha = d47766
$peach = rgb(ecd28b)
$peachAlpha = ecd28b
$yellow = rgb(ebc06d)
$yellowAlpha = ebc06d
$green = rgb(78997a)
$greenAlpha = 78997a
$teal = rgb(87a987)
$tealAlpha = 87a987
$sky = rgb(87a987)
$skyAlpha = 87a987
$sapphire = rgb(a3a9ce)
$sapphireAlpha = a3a9ce
$blue = rgb(a3a9ce)
$blueAlpha = a3a9ce
$lavender = rgb(a3a9ce)
$lavenderAlpha = a3a9ce
$text = rgb(ece1d7)
$textAlpha = ece1d7
$subtext1 = rgb(c1a78e)
$subtext1Alpha = c1a78e
$subtext0 = rgb(c1a78e)
$subtext0Alpha = c1a78e
$overlay2 = rgb(867462)
$overlay2Alpha = 867462
$overlay1 = rgb(867462)
$overlay1Alpha = 867462
$overlay0 = rgb(867462)
$overlay0Alpha = 867462
$surface2 = rgb(867462)
$surface2Alpha = 867462
$surface1 = rgb(34302c)
$surface1Alpha = 34302c
$surface0 = rgb(34302c)
$surface0Alpha = 34302c
$base = rgb(292522)
$baseAlpha = 292522
$mantle = rgb(292522)
$mantleAlpha = 292522
$crust = rgb(292522)
$crustAlpha = 292522

$active_border = rgba(b380b0ee) rgba(a3a9ceee) 45deg
$inactive_border = rgba(867462aa)
$shadow_color = rgba(292522ee)
