# catppuccin-latte tmux colors
set -g pane-border-style fg=#6c6f85
set -g pane-active-border-style fg=#ea76cb
set -g status-bg '#eff1f5'
set -g status-fg '#4c4f69'
set -g status-left '#[fg=#179299]#S #[fg=#df8e1d]|'
set -g status-right '#[fg=#179299]%Y-%m-%d #[fg=#4c4f69]%H:%M #[fg=#df8e1d][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#acb0be,bold]#I:#W#[default]'
