# catppuccin-latte tmux colors
set -g pane-border-style fg=#6c6f85
set -g pane-active-border-style fg=#1d61e9
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#696c82,fg=#eff1f5'
set -g status-left '#[fg=#eff1f5,bold]#S #[fg=#eff1f5]|'
set -g status-right '#[fg=#eff1f5]%Y-%m-%d #[fg=#eff1f5,bold]%H:%M #[fg=#eff1f5][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#1d61e9,fg=#eff1f5,bold] #I:#W #[default]'
