#!/usr/bin/env bats
# repo.bats - sanity checks on the repository's own shipped content.

setup() { load test_helper; }

@test "home layer exists with expected structure" {
  [ -d "$DF_SRC_REPO/home" ]
  [ -d "$DF_SRC_REPO/home/.config" ]
  [ -f "$DF_SRC_REPO/home/.gitconfig" ]
}

@test "shipped bash configuration files are syntactically valid" {
  bash -n "$DF_SRC_REPO/home/.bashrc"
  bash -n "$DF_SRC_REPO/home/.bash_profile"
  local f
  for f in "$DF_SRC_REPO"/home/.config/bash/*.bash; do bash -n "$f"; done
  for f in "$DF_SRC_REPO"/home/.config/shell/completions/*.bash; do bash -n "$f"; done
}

@test "shared POSIX shell files are syntactically valid" {
  local f
  for f in "$DF_SRC_REPO"/home/.profile \
           "$DF_SRC_REPO"/home/.config/shell/*.sh \
           "$DF_SRC_REPO"/home/.config/shell/path.d/*.sh; do
    sh -n "$f"
  done
}

@test "zsh files are syntactically valid (when zsh is available)" {
  command -v zsh >/dev/null 2>&1 || skip "zsh not installed"
  local f
  zsh -n "$DF_SRC_REPO/home/.zshenv"
  zsh -n "$DF_SRC_REPO/home/.zshrc"
  for f in "$DF_SRC_REPO"/home/.config/zsh/*.zsh; do zsh -n "$f"; done
}

@test "tool library files are syntactically valid" {
  local f
  for f in "$DF_SRC_REPO"/lib/*.sh "$DF_SRC_REPO"/lib/commands/*.sh; do
    bash -n "$f"
  done
}

@test "bin/dotfiles is executable and reports its version" {
  [ -x "$DF_SRC_REPO/bin/dotfiles" ]
  run "$DF_SRC_REPO/bin/dotfiles" version
  [ "$status" -eq 0 ]
}

@test "no tracked backup cruft remains in the home layer" {
  [ ! -e "$DF_SRC_REPO/home/.config/hypr/hyprland.conf.bak" ]
  [ ! -e "$DF_SRC_REPO/home/.config/waybar/config.jsonc.bak" ]
  [ ! -e "$DF_SRC_REPO/home/.config/waybar/config.jsonc.fix.bak" ]
}

@test "every shipped theme provides the full seam set" {
  # The seams are generated by tools/build-themes.sh via df_theme_emit_seams;
  # a theme missing one silently falls back to the home layer (or, for btop,
  # made .config/btop single-owner and broke the switch entirely).
  local d name seam missing=""
  for d in "$DF_SRC_REPO"/themes/*/; do
    name=$(basename -- "$d")
    [ "$name" = "auto" ] && continue          # generated at runtime, gitignored
    for seam in .config/hypr/current-theme.conf \
                .config/kitty/current-theme.conf \
                .config/ghostty/themes/current \
                .config/tmux/current-theme.conf \
                .config/waybar/colors.css \
                .config/walker/colors.css \
                .config/shell/theme-env.sh \
                .config/starship.toml \
                .config/opencode/tui.json \
                .config/nvim/lua/dotfiles_theme.lua \
                .config/btop/themes/current.theme \
                .config/background; do
      [ -f "$d/$seam" ] || missing+=" $name:$seam"
    done
  done
  [ -z "$missing" ] || { echo "missing seams:$missing"; false; }
}

@test "the power menu ships a complete elephant menus definition" {
  local m="$DF_SRC_REPO/profiles/hyprland/.config/elephant/menus/powerstate.toml"
  [ -f "$m" ]
  # `name` is what clients address: waybar opens it as `menus:powerstate`, so a
  # rename here silently breaks the battery pill's on-click.
  grep -qx 'name = "powerstate"' "$m"
  local v
  for v in poweroff reboot suspend; do grep -qx "value = \"$v\"" "$m"; done
  # The single shared action MUST interpolate %VALUE%. Without that token
  # elephant does not error -- it pipes the entry's value to the command's
  # stdin instead, so all three entries would run a bare `systemctl`.
  grep -qx 'action = "systemctl %VALUE%"' "$m"
  # Declared order is deliberate (destructive first); alphabetical sorting
  # would reorder these to Reboot / Shutdown / Suspend.
  grep -qx 'fixed_order = true' "$m"
  # menus is a compiled Go plugin, not part of the elephant binary, so a fresh
  # machine has to build it -- providers.list is that manifest.
  grep -qx 'menus' "$DF_SRC_REPO/profiles/hyprland/.config/elephant/providers.list"
}

@test "the power menu's icons are all glyphs, not icon-theme names" {
  # walker routes an icon value to its font label -- the styleable badge --
  # only when the value is non-ASCII and not an absolute path. An ASCII name
  # like "system-shutdown" would silently become an icon-theme lookup instead,
  # so the badge would draw a themed image (or a missing-image placeholder)
  # rather than the glyph, and .item-image-text would style nothing.
  local m="$DF_SRC_REPO/profiles/hyprland/.config/elephant/menus/powerstate.toml"
  local total ascii
  total=$(grep -c '^icon = ' "$m")
  [ "$total" -eq 4 ]                     # menu default + one per entry
  # [ -~] is the printable ASCII range under the C locale.
  ascii=$(LC_ALL=C grep -c '^icon = "[ -~]*"$' "$m" || true)
  [ "$ascii" -eq 0 ]
}

@test "every walker theme styles the power badge" {
  # A theme missing the rule does not error: the glyph falls through to
  # .item-image-text's bare 28px, i.e. no badge at all. powermenu carries it by
  # importing topright's sheet whole rather than being a fourth copy of it, so
  # follow one level of @import before failing.
  local d name css rel
  for d in "$DF_SRC_REPO"/profiles/hyprland/.config/walker/themes/*/; do
    name=$(basename "$d")
    css="$d/style.css"
    [ -f "$css" ] || { echo "$name has no style.css"; false; }
    grep -q '^\.menus-powerstate \.item-image-text {' "$css" && continue
    # @import is resolved by GTK relative to the file containing it.
    rel=$(sed -n 's/^@import "\([^"]*\)";.*/\1/p' "$css" | head -1)
    [ -n "$rel" ] || { echo "no power badge rule in $name/style.css"; false; }
    grep -q '^\.menus-powerstate \.item-image-text {' "$d/$rel" \
      || { echo "no power badge rule reachable from $name/style.css"; false; }
  done
}

@test "the power panel's theme sizes itself to its content" {
  local l="$DF_SRC_REPO/profiles/hyprland/.config/walker/themes/powermenu/layout.xml"
  [ -f "$l" ]
  # The min-* floors must stay at 1 and natural propagation on. A hardcoded
  # floor is exactly what pinned topright's box at 500px wide no matter what
  # --width was passed, and a hand-fitted width clips instead of growing on a
  # machine whose font metrics are wider.
  grep -q '<property name="min-content-width">1</property>' "$l"
  grep -q '<property name="propagate-natural-width">true</property>' "$l"
  grep -q '<property name="propagate-natural-height">true</property>' "$l"
}

@test "waybar's battery pill opens the power menu in its own theme" {
  # -t powermenu is load-bearing, not cosmetic: under the shared topright theme
  # the three rows sit in a box reserved for scrolling pickers.
  grep -q 'walker -m menus:powerstate -t powermenu' \
    "$DF_SRC_REPO/profiles/hyprland/.config/waybar/config.jsonc"
}

@test "every colour walker's stylesheets use is defined by every theme" {
  # GTK drops a whole rule when it references an undefined @colour, so a missing
  # one does not error -- it silently removes whatever that rule drew (e.g. the
  # selected row's background). Overrides are whole files, so a theme carrying a
  # hand-written walker palette misses any colour added to the emitter later;
  # that is exactly how accent_bg_color/highlight_bg_color could have broken the
  # two gruvbox themes when they were split.
  local refs d name colour missing=""
  # Colours referenced across every walker layout, minus the @import at-rule.
  refs=$(grep -ho '@[a-z_]*' "$DF_SRC_REPO"/profiles/hyprland/.config/walker/themes/*/style.css \
         | sed 's/^@//' | grep -vx 'import' | sort -u)
  [ -n "$refs" ] || { echo "found no @colour references in walker stylesheets"; false; }
  for d in "$DF_SRC_REPO"/themes/*/; do
    name=$(basename -- "$d")
    [ "$name" = "auto" ] && continue          # generated at runtime, gitignored
    for colour in $refs; do
      grep -q "^@define-color[[:space:]]\+$colour[[:space:]]" \
        "$d/.config/walker/colors.css" || missing+=" $name:$colour"
    done
  done
  [ -z "$missing" ] || { echo "undefined walker colours:$missing"; false; }
}

@test "every colour waybar's stylesheet uses is defined by every theme" {
  # Same hazard as the walker test above, and the reason it exists: GTK silently
  # drops a rule that references an undefined @colour, so adding a seam to the
  # emitter breaks exactly the themes whose whole colors.css is pinned by an
  # override -- with no error, just a module that stops being coloured. That is
  # how @pill-notify-* would have hit the 15 hand-tuned waybar palettes.
  # style.css defines the battery traffic-light palette itself (deliberately
  # un-themed), so subtract anything it declares locally from the references.
  local css refs local_defs d name colour missing=""
  css="$DF_SRC_REPO/profiles/hyprland/.config/waybar/style.css"
  local_defs=$(grep -o '^@define-color[[:space:]]\+[a-z0-9-]*' "$css" \
               | awk '{print $2}' | sort -u)
  # CSS at-rules share the @ sigil with colour references; waybar's sheet uses
  # @keyframes for the urgent-workspace pulse, so filter the at-rule keywords
  # rather than just @import the way the walker test can get away with.
  refs=$(grep -ho '@[a-z0-9-]*' "$css" | sed 's/^@//' \
         | grep -vxE 'import|define-color|keyframes|media|supports|charset|namespace|font-face' \
         | sort -u | grep -vxF "$local_defs" || true)
  [ -n "$refs" ] || { echo "found no @colour references in waybar stylesheet"; false; }
  for d in "$DF_SRC_REPO"/themes/*/; do
    name=$(basename -- "$d")
    [ "$name" = "auto" ] && continue          # generated at runtime, gitignored
    for colour in $refs; do
      grep -q "^@define-color[[:space:]]\+$colour[[:space:]]" \
        "$d/.config/waybar/colors.css" || missing+=" $name:$colour"
    done
  done
  [ -z "$missing" ] || { echo "undefined waybar colours:$missing"; false; }
}
