#!/usr/bin/env bats
# repo.bats - sanity checks on the repository's own shipped content.

setup() { load test_helper; }

@test "home layer exists with expected structure" {
  [ -d "$DF_SRC_REPO/home" ]
  [ -d "$DF_SRC_REPO/home/.config" ]
  [ -f "$DF_SRC_REPO/home/.gitconfig" ]
}

@test "shipped bash configuration files are syntactically valid" {
  bash -n "$DF_SRC_REPO/home/.bashrc"
  bash -n "$DF_SRC_REPO/home/.bash_profile"
  local f
  for f in "$DF_SRC_REPO"/home/.config/bash/*.bash; do bash -n "$f"; done
  for f in "$DF_SRC_REPO"/home/.config/shell/completions/*.bash; do bash -n "$f"; done
}

@test "shared POSIX shell files are syntactically valid" {
  local f
  for f in "$DF_SRC_REPO"/home/.profile \
           "$DF_SRC_REPO"/home/.config/shell/*.sh \
           "$DF_SRC_REPO"/home/.config/shell/path.d/*.sh; do
    sh -n "$f"
  done
}

@test "zsh files are syntactically valid (when zsh is available)" {
  command -v zsh >/dev/null 2>&1 || skip "zsh not installed"
  local f
  zsh -n "$DF_SRC_REPO/home/.zshenv"
  zsh -n "$DF_SRC_REPO/home/.zshrc"
  for f in "$DF_SRC_REPO"/home/.config/zsh/*.zsh; do zsh -n "$f"; done
}

@test "tool library files are syntactically valid" {
  local f
  for f in "$DF_SRC_REPO"/lib/*.sh "$DF_SRC_REPO"/lib/commands/*.sh; do
    bash -n "$f"
  done
}

@test "bin/dotfiles is executable and reports its version" {
  [ -x "$DF_SRC_REPO/bin/dotfiles" ]
  run "$DF_SRC_REPO/bin/dotfiles" version
  [ "$status" -eq 0 ]
}

@test "no tracked backup cruft remains in the home layer" {
  [ ! -e "$DF_SRC_REPO/home/.config/hypr/hyprland.conf.bak" ]
  [ ! -e "$DF_SRC_REPO/home/.config/waybar/config.jsonc.bak" ]
  [ ! -e "$DF_SRC_REPO/home/.config/waybar/config.jsonc.fix.bak" ]
}

@test "every shipped theme provides the full seam set" {
  # The seams are generated by tools/build-themes.sh via df_theme_emit_seams;
  # a theme missing one silently falls back to the home layer (or, for btop,
  # made .config/btop single-owner and broke the switch entirely).
  local d name seam missing=""
  for d in "$DF_SRC_REPO"/themes/*/; do
    name=$(basename -- "$d")
    [ "$name" = "auto" ] && continue          # generated at runtime, gitignored
    for seam in .config/hypr/current-theme.conf \
                .config/kitty/current-theme.conf \
                .config/ghostty/themes/current \
                .config/tmux/current-theme.conf \
                .config/waybar/colors.css \
                .config/walker/colors.css \
                .config/shell/theme-env.sh \
                .config/starship.toml \
                .config/opencode/tui.json \
                .config/nvim/lua/dotfiles_theme.lua \
                .config/btop/themes/current.theme \
                .config/background; do
      [ -f "$d/$seam" ] || missing+=" $name:$seam"
    done
  done
  [ -z "$missing" ] || { echo "missing seams:$missing"; false; }
}
