# dawnfox tmux colors
set -g pane-border-style fg=#938aa4
set -g pane-active-border-style fg=#6e33ce
set -g status-bg '#faf4ed'
set -g status-fg '#575279'
set -g status-left '#[fg=#3f83a6]#S #[fg=#ac5402]|'
set -g status-right '#[fg=#3f83a6]%Y-%m-%d #[fg=#575279]%H:%M #[fg=#ac5402][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#575279,bold]#I:#W#[default]'
