# kanagawa-wave tmux colors
set -g pane-border-style fg=#727169
set -g pane-active-border-style fg=#b93d40
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#b2af9a,fg=#1f1f28'
set -g status-left '#[fg=#1f1f28,bold]#S #[fg=#47403a]|'
set -g status-right '#[fg=#364245]%Y-%m-%d #[fg=#1f1f28,bold]%H:%M #[fg=#47403a][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#b93d40,fg=#f0f0f0,bold] #I:#W #[default]'
