# monokai-pro hypr/hyprlock colors.
$rosewater = rgb(fcfcfa)
$rosewaterAlpha = fcfcfa
$flamingo = rgb(fcfcfa)
$flamingoAlpha = fcfcfa
$pink = rgb(ab9df2)
$pinkAlpha = ab9df2
$mauve = rgb(ab9df2)
$mauveAlpha = ab9df2
$red = rgb(ff6188)
$redAlpha = ff6188
$maroon = rgb(ff6188)
$maroonAlpha = ff6188
$peach = rgb(ffd866)
$peachAlpha = ffd866
$yellow = rgb(ffd866)
$yellowAlpha = ffd866
$green = rgb(a9dc76)
$greenAlpha = a9dc76
$teal = rgb(78dce8)
$tealAlpha = 78dce8
$sky = rgb(78dce8)
$skyAlpha = 78dce8
$sapphire = rgb(fc9867)
$sapphireAlpha = fc9867
$blue = rgb(fc9867)
$blueAlpha = fc9867
$lavender = rgb(fc9867)
$lavenderAlpha = fc9867
$text = rgb(fcfcfa)
$textAlpha = fcfcfa
$subtext1 = rgb(fcfcfa)
$subtext1Alpha = fcfcfa
$subtext0 = rgb(fcfcfa)
$subtext0Alpha = fcfcfa
$overlay2 = rgb(727072)
$overlay2Alpha = 727072
$overlay1 = rgb(727072)
$overlay1Alpha = 727072
$overlay0 = rgb(727072)
$overlay0Alpha = 727072
$surface2 = rgb(727072)
$surface2Alpha = 727072
$surface1 = rgb(2d2a2e)
$surface1Alpha = 2d2a2e
$surface0 = rgb(2d2a2e)
$surface0Alpha = 2d2a2e
$base = rgb(2d2a2e)
$baseAlpha = 2d2a2e
$mantle = rgb(2d2a2e)
$mantleAlpha = 2d2a2e
$crust = rgb(2d2a2e)
$crustAlpha = 2d2a2e

$active_border = rgba(ab9df2ee) rgba(fc9867ee) 45deg
$inactive_border = rgba(727072aa)
$shadow_color = rgba(2d2a2eee)
