# nordfox tmux colors
set -g pane-border-style fg=#465780
set -g pane-active-border-style fg=#bf616a
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#aaacb0,fg=#2e3440'
set -g status-left '#[fg=#2e3440,bold]#S #[fg=#373c44]|'
set -g status-right '#[fg=#38424c]%Y-%m-%d #[fg=#2e3440,bold]%H:%M #[fg=#373c44][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#bf616a,fg=#141414,bold] #I:#W #[default]'
