# nordfox tmux colors
set -g pane-border-style fg=#465780
set -g pane-active-border-style fg=#b48ead
set -g status-bg '#2e3440'
set -g status-fg '#cdcecf'
set -g status-left '#[fg=#8fbcbb]#S #[fg=#ebcb8b]|'
set -g status-right '#[fg=#8fbcbb]%Y-%m-%d #[fg=#cdcecf]%H:%M #[fg=#ebcb8b][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#e5e9f0,bold]#I:#W#[default]'
