# solarized-light hypr/hyprlock colors.
$rosewater = rgb(eee8d5)
$rosewaterAlpha = eee8d5
$flamingo = rgb(eee8d5)
$flamingoAlpha = eee8d5
$pink = rgb(6c71c4)
$pinkAlpha = 6c71c4
$mauve = rgb(d33682)
$mauveAlpha = d33682
$red = rgb(dc322f)
$redAlpha = dc322f
$maroon = rgb(cb4b16)
$maroonAlpha = cb4b16
$peach = rgb(b58900)
$peachAlpha = b58900
$yellow = rgb(b58900)
$yellowAlpha = b58900
$green = rgb(859900)
$greenAlpha = 859900
$teal = rgb(2aa198)
$tealAlpha = 2aa198
$sky = rgb(2aa198)
$skyAlpha = 2aa198
$sapphire = rgb(268bd2)
$sapphireAlpha = 268bd2
$blue = rgb(268bd2)
$blueAlpha = 268bd2
$lavender = rgb(268bd2)
$lavenderAlpha = 268bd2
$text = rgb(657b83)
$textAlpha = 657b83
$subtext1 = rgb(eee8d5)
$subtext1Alpha = eee8d5
$subtext0 = rgb(eee8d5)
$subtext0Alpha = eee8d5
$overlay2 = rgb(586e75)
$overlay2Alpha = 586e75
$overlay1 = rgb(586e75)
$overlay1Alpha = 586e75
$overlay0 = rgb(586e75)
$overlay0Alpha = 586e75
$surface2 = rgb(586e75)
$surface2Alpha = 586e75
$surface1 = rgb(073642)
$surface1Alpha = 073642
$surface0 = rgb(073642)
$surface0Alpha = 073642
$base = rgb(fdf6e3)
$baseAlpha = fdf6e3
$mantle = rgb(fdf6e3)
$mantleAlpha = fdf6e3
$crust = rgb(fdf6e3)
$crustAlpha = fdf6e3

$active_border = rgba(d33682ee) rgba(268bd2ee) 45deg
$inactive_border = rgba(586e75aa)
$shadow_color = rgba(fdf6e3ee)
