# gruvbox-dark tmux colors
set -g pane-border-style fg=#928374
set -g pane-active-border-style fg=#b16286
set -g status-bg '#282828'
set -g status-fg '#ebdbb2'
set -g status-left '#[fg=#689d6a]#S #[fg=#d79921]|'
set -g status-right '#[fg=#689d6a]%Y-%m-%d #[fg=#ebdbb2]%H:%M #[fg=#d79921][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#a89984,bold]#I:#W#[default]'
