# gruvbox-light tmux colors
set -g pane-border-style fg=#928374
set -g pane-active-border-style fg=#b57614
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#666156,fg=#fbf1c7'
set -g status-left '#[fg=#fbf1c7,bold]#S #[fg=#f2db9e]|'
set -g status-right '#[fg=#dee0b4]%Y-%m-%d #[fg=#fbf1c7,bold]%H:%M #[fg=#f2db9e][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#b57614,fg=#141414,bold] #I:#W #[default]'
