# kanagawa-lotus hypr/hyprlock colors.
$rosewater = rgb(545464)
$rosewaterAlpha = 545464
$flamingo = rgb(545464)
$flamingoAlpha = 545464
$pink = rgb(624c83)
$pinkAlpha = 624c83
$mauve = rgb(b35b79)
$mauveAlpha = b35b79
$red = rgb(c84053)
$redAlpha = c84053
$maroon = rgb(d7474b)
$maroonAlpha = d7474b
$peach = rgb(836f4a)
$peachAlpha = 836f4a
$yellow = rgb(77713f)
$yellowAlpha = 77713f
$green = rgb(6f894e)
$greenAlpha = 6f894e
$teal = rgb(597b75)
$tealAlpha = 597b75
$sky = rgb(597b75)
$skyAlpha = 597b75
$sapphire = rgb(4d699b)
$sapphireAlpha = 4d699b
$blue = rgb(4d699b)
$blueAlpha = 4d699b
$lavender = rgb(6693bf)
$lavenderAlpha = 6693bf
$text = rgb(545464)
$textAlpha = 545464
$subtext1 = rgb(545464)
$subtext1Alpha = 545464
$subtext0 = rgb(545464)
$subtext0Alpha = 545464
$overlay2 = rgb(8a8980)
$overlay2Alpha = 8a8980
$overlay1 = rgb(8a8980)
$overlay1Alpha = 8a8980
$overlay0 = rgb(8a8980)
$overlay0Alpha = 8a8980
$surface2 = rgb(8a8980)
$surface2Alpha = 8a8980
$surface1 = rgb(1f1f28)
$surface1Alpha = 1f1f28
$surface0 = rgb(1f1f28)
$surface0Alpha = 1f1f28
$base = rgb(f2ecbc)
$baseAlpha = f2ecbc
$mantle = rgb(f2ecbc)
$mantleAlpha = f2ecbc
$crust = rgb(f2ecbc)
$crustAlpha = f2ecbc

$active_border = rgba(b35b79ee) rgba(4d699bee) 45deg
$inactive_border = rgba(8a8980aa)
$shadow_color = rgba(f2ecbcee)
