# zenburn tmux colors
set -g pane-border-style fg=#709080
set -g pane-active-border-style fg=#709080
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#b9b9ad,fg=#3f3f3f'
set -g status-left '#[fg=#3f3f3f,bold]#S #[fg=#464543]|'
set -g status-right '#[fg=#434747]%Y-%m-%d #[fg=#3f3f3f,bold]%H:%M #[fg=#464543][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#709080,fg=#141414,bold] #I:#W #[default]'
