# zenburn tmux colors
set -g pane-border-style fg=#709080
set -g pane-active-border-style fg=#dc8cc3
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#3f3f3f,fg=#dcdccc'
set -g status-left '#[fg=#93e0e3]#S #[fg=#d0bf8f]|'
set -g status-right '#[fg=#93e0e3]%Y-%m-%d #[fg=#dcdccc]%H:%M #[fg=#d0bf8f][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#dcdccc,bold]#I:#W#[default]'
