# everforest-dark hypr/hyprlock colors.
$rosewater = rgb(d3c6aa)
$rosewaterAlpha = d3c6aa
$flamingo = rgb(d3c6aa)
$flamingoAlpha = d3c6aa
$pink = rgb(d699b6)
$pinkAlpha = d699b6
$mauve = rgb(d699b6)
$mauveAlpha = d699b6
$red = rgb(e67e80)
$redAlpha = e67e80
$maroon = rgb(e67e80)
$maroonAlpha = e67e80
$peach = rgb(dbbc7f)
$peachAlpha = dbbc7f
$yellow = rgb(dbbc7f)
$yellowAlpha = dbbc7f
$green = rgb(a7c080)
$greenAlpha = a7c080
$teal = rgb(83c092)
$tealAlpha = 83c092
$sky = rgb(83c092)
$skyAlpha = 83c092
$sapphire = rgb(7fbbb3)
$sapphireAlpha = 7fbbb3
$blue = rgb(7fbbb3)
$blueAlpha = 7fbbb3
$lavender = rgb(7fbbb3)
$lavenderAlpha = 7fbbb3
$text = rgb(d3c6aa)
$textAlpha = d3c6aa
$subtext1 = rgb(d3c6aa)
$subtext1Alpha = d3c6aa
$subtext0 = rgb(d3c6aa)
$subtext0Alpha = d3c6aa
$overlay2 = rgb(475258)
$overlay2Alpha = 475258
$overlay1 = rgb(475258)
$overlay1Alpha = 475258
$overlay0 = rgb(475258)
$overlay0Alpha = 475258
$surface2 = rgb(475258)
$surface2Alpha = 475258
$surface1 = rgb(475258)
$surface1Alpha = 475258
$surface0 = rgb(475258)
$surface0Alpha = 475258
$base = rgb(2d353b)
$baseAlpha = 2d353b
$mantle = rgb(2d353b)
$mantleAlpha = 2d353b
$crust = rgb(2d353b)
$crustAlpha = 2d353b

$active_border = rgba(d699b6ee) rgba(7fbbb3ee) 45deg
$inactive_border = rgba(475258aa)
$shadow_color = rgba(2d353bee)
