# monokai-pro tmux colors
set -g pane-border-style fg=#727072
set -g pane-active-border-style fg=#ffd866
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#cececd,fg=#2d2a2e'
set -g status-left '#[fg=#2d2a2e,bold]#S #[fg=#62563c]|'
set -g status-right '#[fg=#40575d]%Y-%m-%d #[fg=#2d2a2e,bold]%H:%M #[fg=#62563c][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#ffd866,fg=#2d2a2e,bold] #I:#W #[default]'
