# tokyonight-day hypr/hyprlock colors.
$rosewater = rgb(6172b0)
$rosewaterAlpha = 6172b0
$flamingo = rgb(6172b0)
$flamingoAlpha = 6172b0
$pink = rgb(9854f1)
$pinkAlpha = 9854f1
$mauve = rgb(9854f1)
$mauveAlpha = 9854f1
$red = rgb(f52a65)
$redAlpha = f52a65
$maroon = rgb(f52a65)
$maroonAlpha = f52a65
$peach = rgb(8c6c3e)
$peachAlpha = 8c6c3e
$yellow = rgb(8c6c3e)
$yellowAlpha = 8c6c3e
$green = rgb(587539)
$greenAlpha = 587539
$teal = rgb(007197)
$tealAlpha = 007197
$sky = rgb(007197)
$skyAlpha = 007197
$sapphire = rgb(2e7de9)
$sapphireAlpha = 2e7de9
$blue = rgb(2e7de9)
$blueAlpha = 2e7de9
$lavender = rgb(2e7de9)
$lavenderAlpha = 2e7de9
$text = rgb(3760bf)
$textAlpha = 3760bf
$subtext1 = rgb(6172b0)
$subtext1Alpha = 6172b0
$subtext0 = rgb(6172b0)
$subtext0Alpha = 6172b0
$overlay2 = rgb(a1a6c5)
$overlay2Alpha = a1a6c5
$overlay1 = rgb(a1a6c5)
$overlay1Alpha = a1a6c5
$overlay0 = rgb(a1a6c5)
$overlay0Alpha = a1a6c5
$surface2 = rgb(a1a6c5)
$surface2Alpha = a1a6c5
$surface1 = rgb(b4b5b9)
$surface1Alpha = b4b5b9
$surface0 = rgb(b4b5b9)
$surface0Alpha = b4b5b9
$base = rgb(e1e2e7)
$baseAlpha = e1e2e7
$mantle = rgb(e1e2e7)
$mantleAlpha = e1e2e7
$crust = rgb(e1e2e7)
$crustAlpha = e1e2e7

$active_border = rgba(9854f1ee) rgba(2e7de9ee) 45deg
$inactive_border = rgba(a1a6c5aa)
$shadow_color = rgba(e1e2e7ee)
