# nordfox hypr/hyprlock colors.
$rosewater = rgb(e5e9f0)
$rosewaterAlpha = e5e9f0
$flamingo = rgb(e5e9f0)
$flamingoAlpha = e5e9f0
$pink = rgb(c895bf)
$pinkAlpha = c895bf
$mauve = rgb(b48ead)
$mauveAlpha = b48ead
$red = rgb(bf616a)
$redAlpha = bf616a
$maroon = rgb(d06f79)
$maroonAlpha = d06f79
$peach = rgb(f0d399)
$peachAlpha = f0d399
$yellow = rgb(ebcb8b)
$yellowAlpha = ebcb8b
$green = rgb(a3be8c)
$greenAlpha = a3be8c
$teal = rgb(8fbcbb)
$tealAlpha = 8fbcbb
$sky = rgb(8fbcbb)
$skyAlpha = 8fbcbb
$sapphire = rgb(81a1c1)
$sapphireAlpha = 81a1c1
$blue = rgb(81a1c1)
$blueAlpha = 81a1c1
$lavender = rgb(8cafd2)
$lavenderAlpha = 8cafd2
$text = rgb(cdcecf)
$textAlpha = cdcecf
$subtext1 = rgb(e5e9f0)
$subtext1Alpha = e5e9f0
$subtext0 = rgb(e5e9f0)
$subtext0Alpha = e5e9f0
$overlay2 = rgb(465780)
$overlay2Alpha = 465780
$overlay1 = rgb(465780)
$overlay1Alpha = 465780
$overlay0 = rgb(465780)
$overlay0Alpha = 465780
$surface2 = rgb(465780)
$surface2Alpha = 465780
$surface1 = rgb(3b4252)
$surface1Alpha = 3b4252
$surface0 = rgb(3b4252)
$surface0Alpha = 3b4252
$base = rgb(2e3440)
$baseAlpha = 2e3440
$mantle = rgb(2e3440)
$mantleAlpha = 2e3440
$crust = rgb(2e3440)
$crustAlpha = 2e3440

$active_border = rgba(b48eadee) rgba(81a1c1ee) 45deg
$inactive_border = rgba(465780aa)
$shadow_color = rgba(2e3440ee)
