# duskfox tmux colors
set -g pane-border-style fg=#47407d
set -g pane-active-border-style fg=#a3be8c
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#47407d,fg=#e0def4'
set -g status-left '#[fg=#e0def4,bold]#S #[fg=#d3b8f2]|'
set -g status-right '#[fg=#aadceb]%Y-%m-%d #[fg=#e0def4,bold]%H:%M #[fg=#f9cb8c][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#a3be8c,fg=#232136,bold] #I:#W #[default]'
