# tokyonight-storm hypr/hyprlock colors.
$rosewater = rgb(a9b1d6)
$rosewaterAlpha = a9b1d6
$flamingo = rgb(a9b1d6)
$flamingoAlpha = a9b1d6
$pink = rgb(bb9af7)
$pinkAlpha = bb9af7
$mauve = rgb(bb9af7)
$mauveAlpha = bb9af7
$red = rgb(f7768e)
$redAlpha = f7768e
$maroon = rgb(f7768e)
$maroonAlpha = f7768e
$peach = rgb(e0af68)
$peachAlpha = e0af68
$yellow = rgb(e0af68)
$yellowAlpha = e0af68
$green = rgb(9ece6a)
$greenAlpha = 9ece6a
$teal = rgb(7dcfff)
$tealAlpha = 7dcfff
$sky = rgb(7dcfff)
$skyAlpha = 7dcfff
$sapphire = rgb(7aa2f7)
$sapphireAlpha = 7aa2f7
$blue = rgb(7aa2f7)
$blueAlpha = 7aa2f7
$lavender = rgb(7aa2f7)
$lavenderAlpha = 7aa2f7
$text = rgb(c0caf5)
$textAlpha = c0caf5
$subtext1 = rgb(a9b1d6)
$subtext1Alpha = a9b1d6
$subtext0 = rgb(a9b1d6)
$subtext0Alpha = a9b1d6
$overlay2 = rgb(414868)
$overlay2Alpha = 414868
$overlay1 = rgb(414868)
$overlay1Alpha = 414868
$overlay0 = rgb(414868)
$overlay0Alpha = 414868
$surface2 = rgb(414868)
$surface2Alpha = 414868
$surface1 = rgb(1d202f)
$surface1Alpha = 1d202f
$surface0 = rgb(1d202f)
$surface0Alpha = 1d202f
$base = rgb(24283b)
$baseAlpha = 24283b
$mantle = rgb(24283b)
$mantleAlpha = 24283b
$crust = rgb(24283b)
$crustAlpha = 24283b

$active_border = rgba(bb9af7ee) rgba(7aa2f7ee) 45deg
$inactive_border = rgba(414868aa)
$shadow_color = rgba(24283bee)
