# dawnfox kitty colors.
foreground              #575279
background              #faf4ed
selection_foreground    #575279
selection_background    #938aa4
url_color               #286983
color0  #f2e9e1
color1  #a5222f
color2  #396847
color3  #ac5402
color4  #286983
color5  #6e33ce
color6  #3f83a6
color7  #575279
color8  #938aa4
color9  #b3434e
color10 #4c8f5c
color11 #c47b28
color12 #4a9db8
color13 #8452d5
color14 #5c9dbb
color15 #575279
cursor                  #575279
cursor_text_color       #faf4ed
active_border_color     #6e33ce
inactive_border_color   #938aa4
