# everforest-light tmux colors
set -g pane-border-style fg=#e6e2cc
set -g pane-active-border-style fg=#3a94c5
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#67737a,fg=#fdf6e3'
set -g status-left '#[fg=#fdf6e3,bold]#S #[fg=#fdf6e3]|'
set -g status-right '#[fg=#fdf6e3]%Y-%m-%d #[fg=#fdf6e3,bold]%H:%M #[fg=#fdf6e3][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#3a94c5,fg=#141414,bold] #I:#W #[default]'
