# duskfox hypr/hyprlock colors.
$rosewater = rgb(e0def4)
$rosewaterAlpha = e0def4
$flamingo = rgb(e0def4)
$flamingoAlpha = e0def4
$pink = rgb(d3b8f2)
$pinkAlpha = d3b8f2
$mauve = rgb(c4a7e7)
$mauveAlpha = c4a7e7
$red = rgb(eb6f92)
$redAlpha = eb6f92
$maroon = rgb(eb98b5)
$maroonAlpha = eb98b5
$peach = rgb(f9cb8c)
$peachAlpha = f9cb8c
$yellow = rgb(f6c177)
$yellowAlpha = f6c177
$green = rgb(a3be8c)
$greenAlpha = a3be8c
$teal = rgb(9ccfd8)
$tealAlpha = 9ccfd8
$sky = rgb(9ccfd8)
$skyAlpha = 9ccfd8
$sapphire = rgb(569fba)
$sapphireAlpha = 569fba
$blue = rgb(569fba)
$blueAlpha = 569fba
$lavender = rgb(65b1cd)
$lavenderAlpha = 65b1cd
$text = rgb(e0def4)
$textAlpha = e0def4
$subtext1 = rgb(e0def4)
$subtext1Alpha = e0def4
$subtext0 = rgb(e0def4)
$subtext0Alpha = e0def4
$overlay2 = rgb(47407d)
$overlay2Alpha = 47407d
$overlay1 = rgb(47407d)
$overlay1Alpha = 47407d
$overlay0 = rgb(47407d)
$overlay0Alpha = 47407d
$surface2 = rgb(47407d)
$surface2Alpha = 47407d
$surface1 = rgb(393552)
$surface1Alpha = 393552
$surface0 = rgb(393552)
$surface0Alpha = 393552
$base = rgb(232136)
$baseAlpha = 232136
$mantle = rgb(232136)
$mantleAlpha = 232136
$crust = rgb(232136)
$crustAlpha = 232136

$active_border = rgba(c4a7e7ee) rgba(569fbaee) 45deg
$inactive_border = rgba(47407daa)
$shadow_color = rgba(232136ee)
