# gruvbox-light hypr/hyprlock colors.
$rosewater = rgb(7c6f64)
$rosewaterAlpha = 7c6f64
$flamingo = rgb(7c6f64)
$flamingoAlpha = 7c6f64
$pink = rgb(8f3f71)
$pinkAlpha = 8f3f71
$mauve = rgb(b16286)
$mauveAlpha = b16286
$red = rgb(cc241d)
$redAlpha = cc241d
$maroon = rgb(9d0006)
$maroonAlpha = 9d0006
$peach = rgb(b57614)
$peachAlpha = b57614
$yellow = rgb(d79921)
$yellowAlpha = d79921
$green = rgb(98971a)
$greenAlpha = 98971a
$teal = rgb(689d6a)
$tealAlpha = 689d6a
$sky = rgb(689d6a)
$skyAlpha = 689d6a
$sapphire = rgb(458588)
$sapphireAlpha = 458588
$blue = rgb(458588)
$blueAlpha = 458588
$lavender = rgb(076678)
$lavenderAlpha = 076678
$text = rgb(3c3836)
$textAlpha = 3c3836
$subtext1 = rgb(7c6f64)
$subtext1Alpha = 7c6f64
$subtext0 = rgb(7c6f64)
$subtext0Alpha = 7c6f64
$overlay2 = rgb(928374)
$overlay2Alpha = 928374
$overlay1 = rgb(928374)
$overlay1Alpha = 928374
$overlay0 = rgb(928374)
$overlay0Alpha = 928374
$surface2 = rgb(928374)
$surface2Alpha = 928374
$surface1 = rgb(fbf1c7)
$surface1Alpha = fbf1c7
$surface0 = rgb(fbf1c7)
$surface0Alpha = fbf1c7
$base = rgb(fbf1c7)
$baseAlpha = fbf1c7
$mantle = rgb(fbf1c7)
$mantleAlpha = fbf1c7
$crust = rgb(fbf1c7)
$crustAlpha = fbf1c7

$active_border = rgba(b16286ee) rgba(458588ee) 45deg
$inactive_border = rgba(928374aa)
$shadow_color = rgba(fbf1c7ee)
