# terafox tmux colors
set -g pane-border-style fg=#4e5157
set -g pane-active-border-style fg=#ad5c7c
set -g status-bg '#152528'
set -g status-fg '#e6eaea'
set -g status-left '#[fg=#a1cdd8]#S #[fg=#fda47f]|'
set -g status-right '#[fg=#a1cdd8]%Y-%m-%d #[fg=#e6eaea]%H:%M #[fg=#fda47f][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#eaeeee,bold]#I:#W#[default]'
