# terafox tmux colors
set -g pane-border-style fg=#4e5157
set -g pane-active-border-style fg=#e85c51
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#b8bfbf,fg=#152528'
set -g status-left '#[fg=#152528,bold]#S #[fg=#4f453e]|'
set -g status-right '#[fg=#384f54]%Y-%m-%d #[fg=#152528,bold]%H:%M #[fg=#4f453e][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#e85c51,fg=#152528,bold] #I:#W #[default]'
