# palenight hypr/hyprlock colors.
$rosewater = rgb(d0d0d0)
$rosewaterAlpha = d0d0d0
$flamingo = rgb(d0d0d0)
$flamingoAlpha = d0d0d0
$pink = rgb(e1acff)
$pinkAlpha = e1acff
$mauve = rgb(c792ea)
$mauveAlpha = c792ea
$red = rgb(f07178)
$redAlpha = f07178
$maroon = rgb(ff8b92)
$maroonAlpha = ff8b92
$peach = rgb(ffe585)
$peachAlpha = ffe585
$yellow = rgb(ffcb6b)
$yellowAlpha = ffcb6b
$green = rgb(c3e88d)
$greenAlpha = c3e88d
$teal = rgb(89ddff)
$tealAlpha = 89ddff
$sky = rgb(89ddff)
$skyAlpha = 89ddff
$sapphire = rgb(82aaff)
$sapphireAlpha = 82aaff
$blue = rgb(82aaff)
$blueAlpha = 82aaff
$lavender = rgb(9cc4ff)
$lavenderAlpha = 9cc4ff
$text = rgb(a6accd)
$textAlpha = a6accd
$subtext1 = rgb(d0d0d0)
$subtext1Alpha = d0d0d0
$subtext0 = rgb(d0d0d0)
$subtext0Alpha = d0d0d0
$overlay2 = rgb(434758)
$overlay2Alpha = 434758
$overlay1 = rgb(434758)
$overlay1Alpha = 434758
$overlay0 = rgb(434758)
$overlay0Alpha = 434758
$surface2 = rgb(434758)
$surface2Alpha = 434758
$surface1 = rgb(292d3e)
$surface1Alpha = 292d3e
$surface0 = rgb(292d3e)
$surface0Alpha = 292d3e
$base = rgb(292d3e)
$baseAlpha = 292d3e
$mantle = rgb(292d3e)
$mantleAlpha = 292d3e
$crust = rgb(292d3e)
$crustAlpha = 292d3e

$active_border = rgba(c792eaee) rgba(82aaffee) 45deg
$inactive_border = rgba(434758aa)
$shadow_color = rgba(292d3eee)
