# nordfox kitty colors.
foreground              #cdcecf
background              #2e3440
selection_foreground    #cdcecf
selection_background    #465780
url_color               #81a1c1
color0  #3b4252
color1  #bf616a
color2  #a3be8c
color3  #ebcb8b
color4  #81a1c1
color5  #b48ead
color6  #8fbcbb
color7  #e5e9f0
color8  #465780
color9  #d06f79
color10 #b1d196
color11 #f0d399
color12 #8cafd2
color13 #c895bf
color14 #93ccdc
color15 #e7ecf4
cursor                  #cdcecf
cursor_text_color       #2e3440
active_border_color     #b48ead
inactive_border_color   #465780
