# kanagawa-lotus tmux colors
set -g pane-border-style fg=#8a8980
set -g pane-active-border-style fg=#b35b79
set -g status-bg '#f2ecbc'
set -g status-fg '#545464'
set -g status-left '#[fg=#597b75]#S #[fg=#77713f]|'
set -g status-right '#[fg=#597b75]%Y-%m-%d #[fg=#545464]%H:%M #[fg=#77713f][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#545464,bold]#I:#W#[default]'
