# kanagawa-lotus tmux colors
set -g pane-border-style fg=#8a8980
set -g pane-active-border-style fg=#be3d4f
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#6b6970,fg=#f2ecbc'
set -g status-left '#[fg=#f2ecbc,bold]#S #[fg=#f2ecbc]|'
set -g status-right '#[fg=#f2ecbc]%Y-%m-%d #[fg=#f2ecbc,bold]%H:%M #[fg=#f2ecbc][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#be3d4f,fg=#f0f0f0,bold] #I:#W #[default]'
