# catppuccin-frappe tmux colors
set -g pane-border-style fg=#626880
set -g pane-active-border-style fg=#e5c890
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#a5aecf,fg=#303446'
set -g status-left '#[fg=#303446,bold]#S #[fg=#393b4a]|'
set -g status-right '#[fg=#384352]%Y-%m-%d #[fg=#303446,bold]%H:%M #[fg=#393b4a][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#e5c890,fg=#303446,bold] #I:#W #[default]'
