# solarized-dark kitty colors.
foreground              #839496
background              #002b36
selection_foreground    #839496
selection_background    #586e75
url_color               #268bd2
color0  #073642
color1  #dc322f
color2  #859900
color3  #b58900
color4  #268bd2
color5  #d33682
color6  #2aa198
color7  #eee8d5
color8  #586e75
color9  #cb4b16
color10 #859900
color11 #b58900
color12 #268bd2
color13 #6c71c4
color14 #93a1a1
color15 #fdf6e3
cursor                  #839496
cursor_text_color       #002b36
active_border_color     #d33682
inactive_border_color   #586e75
