# tokyonight-night tmux colors
set -g pane-border-style fg=#414868
set -g pane-active-border-style fg=#f7768e
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#9ba4c7,fg=#1a1b26'
set -g status-left '#[fg=#1a1b26,bold]#S #[fg=#423933]|'
set -g status-right '#[fg=#293647]%Y-%m-%d #[fg=#1a1b26,bold]%H:%M #[fg=#423933][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#f7768e,fg=#1a1b26,bold] #I:#W #[default]'
