# everforest-light hypr/hyprlock colors.
$rosewater = rgb(5c6a72)
$rosewaterAlpha = 5c6a72
$flamingo = rgb(5c6a72)
$flamingoAlpha = 5c6a72
$pink = rgb(df69ba)
$pinkAlpha = df69ba
$mauve = rgb(df69ba)
$mauveAlpha = df69ba
$red = rgb(f85552)
$redAlpha = f85552
$maroon = rgb(f85552)
$maroonAlpha = f85552
$peach = rgb(dfa000)
$peachAlpha = dfa000
$yellow = rgb(dfa000)
$yellowAlpha = dfa000
$green = rgb(8da101)
$greenAlpha = 8da101
$teal = rgb(35a77c)
$tealAlpha = 35a77c
$sky = rgb(35a77c)
$skyAlpha = 35a77c
$sapphire = rgb(3a94c5)
$sapphireAlpha = 3a94c5
$blue = rgb(3a94c5)
$blueAlpha = 3a94c5
$lavender = rgb(3a94c5)
$lavenderAlpha = 3a94c5
$text = rgb(5c6a72)
$textAlpha = 5c6a72
$subtext1 = rgb(5c6a72)
$subtext1Alpha = 5c6a72
$subtext0 = rgb(5c6a72)
$subtext0Alpha = 5c6a72
$overlay2 = rgb(e6e2cc)
$overlay2Alpha = e6e2cc
$overlay1 = rgb(e6e2cc)
$overlay1Alpha = e6e2cc
$overlay0 = rgb(e6e2cc)
$overlay0Alpha = e6e2cc
$surface2 = rgb(e6e2cc)
$surface2Alpha = e6e2cc
$surface1 = rgb(e6e2cc)
$surface1Alpha = e6e2cc
$surface0 = rgb(e6e2cc)
$surface0Alpha = e6e2cc
$base = rgb(fdf6e3)
$baseAlpha = fdf6e3
$mantle = rgb(fdf6e3)
$mantleAlpha = fdf6e3
$crust = rgb(fdf6e3)
$crustAlpha = fdf6e3

$active_border = rgba(df69baee) rgba(3a94c5ee) 45deg
$inactive_border = rgba(e6e2ccaa)
$shadow_color = rgba(fdf6e3ee)
