# nord tmux colors
set -g pane-border-style fg=#4c566a
set -g pane-active-border-style fg=#bf616a
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#b3b9c4,fg=#2e3440'
set -g status-left '#[fg=#2e3440,bold]#S #[fg=#414348]|'
set -g status-right '#[fg=#3c4956]%Y-%m-%d #[fg=#2e3440,bold]%H:%M #[fg=#414348][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#bf616a,fg=#141414,bold] #I:#W #[default]'
