# zenburn hypr/hyprlock colors.
$rosewater = rgb(dcdccc)
$rosewaterAlpha = dcdccc
$flamingo = rgb(dcdccc)
$flamingoAlpha = dcdccc
$pink = rgb(ec93d3)
$pinkAlpha = ec93d3
$mauve = rgb(dc8cc3)
$mauveAlpha = dc8cc3
$red = rgb(cc9393)
$redAlpha = cc9393
$maroon = rgb(dca3a3)
$maroonAlpha = dca3a3
$peach = rgb(f0dfaf)
$peachAlpha = f0dfaf
$yellow = rgb(d0bf8f)
$yellowAlpha = d0bf8f
$green = rgb(7f9f7f)
$greenAlpha = 7f9f7f
$teal = rgb(93e0e3)
$tealAlpha = 93e0e3
$sky = rgb(93e0e3)
$skyAlpha = 93e0e3
$sapphire = rgb(6ca0a3)
$sapphireAlpha = 6ca0a3
$blue = rgb(6ca0a3)
$blueAlpha = 6ca0a3
$lavender = rgb(8cd0d3)
$lavenderAlpha = 8cd0d3
$text = rgb(dcdccc)
$textAlpha = dcdccc
$subtext1 = rgb(dcdccc)
$subtext1Alpha = dcdccc
$subtext0 = rgb(dcdccc)
$subtext0Alpha = dcdccc
$overlay2 = rgb(709080)
$overlay2Alpha = 709080
$overlay1 = rgb(709080)
$overlay1Alpha = 709080
$overlay0 = rgb(709080)
$overlay0Alpha = 709080
$surface2 = rgb(709080)
$surface2Alpha = 709080
$surface1 = rgb(3f3f3f)
$surface1Alpha = 3f3f3f
$surface0 = rgb(3f3f3f)
$surface0Alpha = 3f3f3f
$base = rgb(3f3f3f)
$baseAlpha = 3f3f3f
$mantle = rgb(3f3f3f)
$mantleAlpha = 3f3f3f
$crust = rgb(3f3f3f)
$crustAlpha = 3f3f3f

$active_border = rgba(dc8cc3ee) rgba(6ca0a3ee) 45deg
$inactive_border = rgba(709080aa)
$shadow_color = rgba(3f3f3fee)
