# kanagawa-dragon hypr/hyprlock colors.
$rosewater = rgb(c8c093)
$rosewaterAlpha = c8c093
$flamingo = rgb(c8c093)
$flamingoAlpha = c8c093
$pink = rgb(938aa9)
$pinkAlpha = 938aa9
$mauve = rgb(a292a3)
$mauveAlpha = a292a3
$red = rgb(c4746e)
$redAlpha = c4746e
$maroon = rgb(e46876)
$maroonAlpha = e46876
$peach = rgb(e6c384)
$peachAlpha = e6c384
$yellow = rgb(c4b28a)
$yellowAlpha = c4b28a
$green = rgb(8a9a7b)
$greenAlpha = 8a9a7b
$teal = rgb(8ea4a2)
$tealAlpha = 8ea4a2
$sky = rgb(8ea4a2)
$skyAlpha = 8ea4a2
$sapphire = rgb(8ba4b0)
$sapphireAlpha = 8ba4b0
$blue = rgb(8ba4b0)
$blueAlpha = 8ba4b0
$lavender = rgb(7fb4ca)
$lavenderAlpha = 7fb4ca
$text = rgb(c5c9c5)
$textAlpha = c5c9c5
$subtext1 = rgb(c8c093)
$subtext1Alpha = c8c093
$subtext0 = rgb(c8c093)
$subtext0Alpha = c8c093
$overlay2 = rgb(a6a69c)
$overlay2Alpha = a6a69c
$overlay1 = rgb(a6a69c)
$overlay1Alpha = a6a69c
$overlay0 = rgb(a6a69c)
$overlay0Alpha = a6a69c
$surface2 = rgb(a6a69c)
$surface2Alpha = a6a69c
$surface1 = rgb(0d0c0c)
$surface1Alpha = 0d0c0c
$surface0 = rgb(0d0c0c)
$surface0Alpha = 0d0c0c
$base = rgb(181616)
$baseAlpha = 181616
$mantle = rgb(181616)
$mantleAlpha = 181616
$crust = rgb(181616)
$crustAlpha = 181616

$active_border = rgba(a292a3ee) rgba(8ba4b0ee) 45deg
$inactive_border = rgba(a6a69caa)
$shadow_color = rgba(181616ee)
