# ayu-dark hypr/hyprlock colors.
$rosewater = rgb(c7c7c7)
$rosewaterAlpha = c7c7c7
$flamingo = rgb(c7c7c7)
$flamingoAlpha = c7c7c7
$pink = rgb(ffee99)
$pinkAlpha = ffee99
$mauve = rgb(fae994)
$mauveAlpha = fae994
$red = rgb(ea6c73)
$redAlpha = ea6c73
$maroon = rgb(f07178)
$maroonAlpha = f07178
$peach = rgb(ffb454)
$peachAlpha = ffb454
$yellow = rgb(f9af4f)
$yellowAlpha = f9af4f
$green = rgb(91b362)
$greenAlpha = 91b362
$teal = rgb(90e1c6)
$tealAlpha = 90e1c6
$sky = rgb(90e1c6)
$skyAlpha = 90e1c6
$sapphire = rgb(53bdfa)
$sapphireAlpha = 53bdfa
$blue = rgb(53bdfa)
$blueAlpha = 53bdfa
$lavender = rgb(59c2ff)
$lavenderAlpha = 59c2ff
$text = rgb(b3b1ad)
$textAlpha = b3b1ad
$subtext1 = rgb(c7c7c7)
$subtext1Alpha = c7c7c7
$subtext0 = rgb(c7c7c7)
$subtext0Alpha = c7c7c7
$overlay2 = rgb(686868)
$overlay2Alpha = 686868
$overlay1 = rgb(686868)
$overlay1Alpha = 686868
$overlay0 = rgb(686868)
$overlay0Alpha = 686868
$surface2 = rgb(686868)
$surface2Alpha = 686868
$surface1 = rgb(01060e)
$surface1Alpha = 01060e
$surface0 = rgb(01060e)
$surface0Alpha = 01060e
$base = rgb(0a0e14)
$baseAlpha = 0a0e14
$mantle = rgb(0a0e14)
$mantleAlpha = 0a0e14
$crust = rgb(0a0e14)
$crustAlpha = 0a0e14

$active_border = rgba(fae994ee) rgba(53bdfaee) 45deg
$inactive_border = rgba(686868aa)
$shadow_color = rgba(0a0e14ee)
