# rose-pine-dawn tmux colors
set -g pane-border-style fg=#9893a5
set -g pane-active-border-style fg=#907aa9
set -g status-bg '#faf4ed'
set -g status-fg '#575279'
set -g status-left '#[fg=#d7827e]#S #[fg=#ea9d34]|'
set -g status-right '#[fg=#d7827e]%Y-%m-%d #[fg=#575279]%H:%M #[fg=#ea9d34][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#575279,bold]#I:#W#[default]'
