# rose-pine-dawn tmux colors
set -g pane-border-style fg=#9893a5
set -g pane-active-border-style fg=#ea9d34
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#706b8b,fg=#faf4ed'
set -g status-left '#[fg=#faf4ed,bold]#S #[fg=#faf4ed]|'
set -g status-right '#[fg=#faf4ed]%Y-%m-%d #[fg=#faf4ed,bold]%H:%M #[fg=#faf4ed][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#ea9d34,fg=#141414,bold] #I:#W #[default]'
