# dracula hypr/hyprlock colors.
$rosewater = rgb(f8f8f2)
$rosewaterAlpha = f8f8f2
$flamingo = rgb(f8f8f2)
$flamingoAlpha = f8f8f2
$pink = rgb(ff92df)
$pinkAlpha = ff92df
$mauve = rgb(ff79c6)
$mauveAlpha = ff79c6
$red = rgb(ff5555)
$redAlpha = ff5555
$maroon = rgb(ff6e6e)
$maroonAlpha = ff6e6e
$peach = rgb(ffffa5)
$peachAlpha = ffffa5
$yellow = rgb(f1fa8c)
$yellowAlpha = f1fa8c
$green = rgb(50fa7b)
$greenAlpha = 50fa7b
$teal = rgb(8be9fd)
$tealAlpha = 8be9fd
$sky = rgb(8be9fd)
$skyAlpha = 8be9fd
$sapphire = rgb(bd93f9)
$sapphireAlpha = bd93f9
$blue = rgb(bd93f9)
$blueAlpha = bd93f9
$lavender = rgb(d6acff)
$lavenderAlpha = d6acff
$text = rgb(f8f8f2)
$textAlpha = f8f8f2
$subtext1 = rgb(f8f8f2)
$subtext1Alpha = f8f8f2
$subtext0 = rgb(f8f8f2)
$subtext0Alpha = f8f8f2
$overlay2 = rgb(6272a4)
$overlay2Alpha = 6272a4
$overlay1 = rgb(6272a4)
$overlay1Alpha = 6272a4
$overlay0 = rgb(6272a4)
$overlay0Alpha = 6272a4
$surface2 = rgb(6272a4)
$surface2Alpha = 6272a4
$surface1 = rgb(21222c)
$surface1Alpha = 21222c
$surface0 = rgb(21222c)
$surface0Alpha = 21222c
$base = rgb(282a36)
$baseAlpha = 282a36
$mantle = rgb(282a36)
$mantleAlpha = 282a36
$crust = rgb(282a36)
$crustAlpha = 282a36

$active_border = rgba(ff79c6ee) rgba(bd93f9ee) 45deg
$inactive_border = rgba(6272a4aa)
$shadow_color = rgba(282a36ee)
