# onedark hypr/hyprlock colors.
$rosewater = rgb(abb2bf)
$rosewaterAlpha = abb2bf
$flamingo = rgb(abb2bf)
$flamingoAlpha = abb2bf
$pink = rgb(c678dd)
$pinkAlpha = c678dd
$mauve = rgb(c678dd)
$mauveAlpha = c678dd
$red = rgb(e06c75)
$redAlpha = e06c75
$maroon = rgb(e06c75)
$maroonAlpha = e06c75
$peach = rgb(e5c07b)
$peachAlpha = e5c07b
$yellow = rgb(e5c07b)
$yellowAlpha = e5c07b
$green = rgb(98c379)
$greenAlpha = 98c379
$teal = rgb(56b6c2)
$tealAlpha = 56b6c2
$sky = rgb(56b6c2)
$skyAlpha = 56b6c2
$sapphire = rgb(61afef)
$sapphireAlpha = 61afef
$blue = rgb(61afef)
$blueAlpha = 61afef
$lavender = rgb(61afef)
$lavenderAlpha = 61afef
$text = rgb(abb2bf)
$textAlpha = abb2bf
$subtext1 = rgb(abb2bf)
$subtext1Alpha = abb2bf
$subtext0 = rgb(abb2bf)
$subtext0Alpha = abb2bf
$overlay2 = rgb(545862)
$overlay2Alpha = 545862
$overlay1 = rgb(545862)
$overlay1Alpha = 545862
$overlay0 = rgb(545862)
$overlay0Alpha = 545862
$surface2 = rgb(545862)
$surface2Alpha = 545862
$surface1 = rgb(282c34)
$surface1Alpha = 282c34
$surface0 = rgb(282c34)
$surface0Alpha = 282c34
$base = rgb(282c34)
$baseAlpha = 282c34
$mantle = rgb(282c34)
$mantleAlpha = 282c34
$crust = rgb(282c34)
$crustAlpha = 282c34

$active_border = rgba(c678ddee) rgba(61afefee) 45deg
$inactive_border = rgba(545862aa)
$shadow_color = rgba(282c34ee)
