# monokai tmux colors
set -g pane-border-style fg=#75715e
set -g pane-active-border-style fg=#ae81ff
set -g status-bg '#272822'
set -g status-fg '#f8f8f2'
set -g status-left '#[fg=#a1efe4]#S #[fg=#f4bf75]|'
set -g status-right '#[fg=#a1efe4]%Y-%m-%d #[fg=#f8f8f2]%H:%M #[fg=#f4bf75][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#f8f8f2,bold]#I:#W#[default]'
