# monokai tmux colors
set -g pane-border-style fg=#75715e
set -g pane-active-border-style fg=#a6e22e
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#cacac4,fg=#272822'
set -g status-left '#[fg=#272822,bold]#S #[fg=#5a4e37]|'
set -g status-right '#[fg=#3f5049]%Y-%m-%d #[fg=#272822,bold]%H:%M #[fg=#5a4e37][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#a6e22e,fg=#272822,bold] #I:#W #[default]'
