# dawnfox hypr/hyprlock colors.
$rosewater = rgb(575279)
$rosewaterAlpha = 575279
$flamingo = rgb(575279)
$flamingoAlpha = 575279
$pink = rgb(8452d5)
$pinkAlpha = 8452d5
$mauve = rgb(6e33ce)
$mauveAlpha = 6e33ce
$red = rgb(a5222f)
$redAlpha = a5222f
$maroon = rgb(b3434e)
$maroonAlpha = b3434e
$peach = rgb(c47b28)
$peachAlpha = c47b28
$yellow = rgb(ac5402)
$yellowAlpha = ac5402
$green = rgb(396847)
$greenAlpha = 396847
$teal = rgb(3f83a6)
$tealAlpha = 3f83a6
$sky = rgb(3f83a6)
$skyAlpha = 3f83a6
$sapphire = rgb(286983)
$sapphireAlpha = 286983
$blue = rgb(286983)
$blueAlpha = 286983
$lavender = rgb(4a9db8)
$lavenderAlpha = 4a9db8
$text = rgb(575279)
$textAlpha = 575279
$subtext1 = rgb(575279)
$subtext1Alpha = 575279
$subtext0 = rgb(575279)
$subtext0Alpha = 575279
$overlay2 = rgb(938aa4)
$overlay2Alpha = 938aa4
$overlay1 = rgb(938aa4)
$overlay1Alpha = 938aa4
$overlay0 = rgb(938aa4)
$overlay0Alpha = 938aa4
$surface2 = rgb(938aa4)
$surface2Alpha = 938aa4
$surface1 = rgb(f2e9e1)
$surface1Alpha = f2e9e1
$surface0 = rgb(f2e9e1)
$surface0Alpha = f2e9e1
$base = rgb(faf4ed)
$baseAlpha = faf4ed
$mantle = rgb(faf4ed)
$mantleAlpha = faf4ed
$crust = rgb(faf4ed)
$crustAlpha = faf4ed

$active_border = rgba(6e33ceee) rgba(286983ee) 45deg
$inactive_border = rgba(938aa4aa)
$shadow_color = rgba(faf4edee)
