# carbonfox tmux colors
set -g pane-border-style fg=#484848
set -g pane-active-border-style fg=#52bdff
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#c2c3c6,fg=#161616'
set -g status-left '#[fg=#161616,bold]#S #[fg=#105958]|'
set -g status-right '#[fg=#225473]%Y-%m-%d #[fg=#161616,bold]%H:%M #[fg=#105958][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#52bdff,fg=#161616,bold] #I:#W #[default]'
