# carbonfox tmux colors
set -g pane-border-style fg=#484848
set -g pane-active-border-style fg=#be95ff
set -g status-bg '#161616'
set -g status-fg '#f2f4f8'
set -g status-left '#[fg=#33b1ff]#S #[fg=#08bdba]|'
set -g status-right '#[fg=#33b1ff]%Y-%m-%d #[fg=#f2f4f8]%H:%M #[fg=#08bdba][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#dfdfe0,bold]#I:#W#[default]'
