# tokyonight-storm tmux colors
set -g pane-border-style fg=#414868
set -g pane-active-border-style fg=#bb9af7
set -g status-bg '#24283b'
set -g status-fg '#c0caf5'
set -g status-left '#[fg=#7dcfff]#S #[fg=#e0af68]|'
set -g status-right '#[fg=#7dcfff]%Y-%m-%d #[fg=#c0caf5]%H:%M #[fg=#e0af68][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#a9b1d6,bold]#I:#W#[default]'
