# everforest-dark tmux colors
set -g pane-border-style fg=#475258
set -g pane-active-border-style fg=#d699b6
set -g status-bg '#2d353b'
set -g status-fg '#d3c6aa'
set -g status-left '#[fg=#83c092]#S #[fg=#dbbc7f]|'
set -g status-right '#[fg=#83c092]%Y-%m-%d #[fg=#d3c6aa]%H:%M #[fg=#dbbc7f][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#d3c6aa,bold]#I:#W#[default]'
