# everforest-dark tmux colors
set -g pane-border-style fg=#475258
set -g pane-active-border-style fg=#475258
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#aea692,fg=#2d353b'
set -g status-left '#[fg=#2d353b,bold]#S #[fg=#363c3e]|'
set -g status-right '#[fg=#313c3f]%Y-%m-%d #[fg=#2d353b,bold]%H:%M #[fg=#363c3e][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#475258,fg=#d3c6aa,bold] #I:#W #[default]'
