# oxocarbon hypr/hyprlock colors.
$rosewater = rgb(dde1e6)
$rosewaterAlpha = dde1e6
$flamingo = rgb(dde1e6)
$flamingoAlpha = dde1e6
$pink = rgb(ee5396)
$pinkAlpha = ee5396
$mauve = rgb(ee5396)
$mauveAlpha = ee5396
$red = rgb(ff7eb6)
$redAlpha = ff7eb6
$maroon = rgb(ff7eb6)
$maroonAlpha = ff7eb6
$peach = rgb(be95ff)
$peachAlpha = be95ff
$yellow = rgb(be95ff)
$yellowAlpha = be95ff
$green = rgb(42be65)
$greenAlpha = 42be65
$teal = rgb(3ddbd9)
$tealAlpha = 3ddbd9
$sky = rgb(3ddbd9)
$skyAlpha = 3ddbd9
$sapphire = rgb(33b1ff)
$sapphireAlpha = 33b1ff
$blue = rgb(33b1ff)
$blueAlpha = 33b1ff
$lavender = rgb(33b1ff)
$lavenderAlpha = 33b1ff
$text = rgb(f2f4f8)
$textAlpha = f2f4f8
$subtext1 = rgb(dde1e6)
$subtext1Alpha = dde1e6
$subtext0 = rgb(dde1e6)
$subtext0Alpha = dde1e6
$overlay2 = rgb(525252)
$overlay2Alpha = 525252
$overlay1 = rgb(525252)
$overlay1Alpha = 525252
$overlay0 = rgb(525252)
$overlay0Alpha = 525252
$surface2 = rgb(525252)
$surface2Alpha = 525252
$surface1 = rgb(161616)
$surface1Alpha = 161616
$surface0 = rgb(161616)
$surface0Alpha = 161616
$base = rgb(161616)
$baseAlpha = 161616
$mantle = rgb(161616)
$mantleAlpha = 161616
$crust = rgb(161616)
$crustAlpha = 161616

$active_border = rgba(ee5396ee) rgba(33b1ffee) 45deg
$inactive_border = rgba(525252aa)
$shadow_color = rgba(161616ee)
