# zenburn kitty colors.
foreground              #dcdccc
background              #3f3f3f
selection_foreground    #dcdccc
selection_background    #709080
url_color               #6ca0a3
color0  #3f3f3f
color1  #cc9393
color2  #7f9f7f
color3  #d0bf8f
color4  #6ca0a3
color5  #dc8cc3
color6  #93e0e3
color7  #dcdccc
color8  #709080
color9  #dca3a3
color10 #bfebbf
color11 #f0dfaf
color12 #8cd0d3
color13 #ec93d3
color14 #93e0e3
color15 #ffffff
cursor                  #dcdccc
cursor_text_color       #3f3f3f
active_border_color     #dc8cc3
inactive_border_color   #709080
