# tokyonight-day tmux colors
set -g pane-border-style fg=#a1a6c5
set -g pane-active-border-style fg=#9854f1
set -g status-bg '#e1e2e7'
set -g status-fg '#3760bf'
set -g status-left '#[fg=#007197]#S #[fg=#8c6c3e]|'
set -g status-right '#[fg=#007197]%Y-%m-%d #[fg=#3760bf]%H:%M #[fg=#8c6c3e][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#6172b0,bold]#I:#W#[default]'
