# tokyonight-day tmux colors
set -g pane-border-style fg=#a1a6c5
set -g pane-active-border-style fg=#587539
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#3760bf,fg=#e1e2e7'
set -g status-left '#[fg=#e1e2e7,bold]#S #[fg=#e1e2e7]|'
set -g status-right '#[fg=#e1e2e7]%Y-%m-%d #[fg=#e1e2e7,bold]%H:%M #[fg=#e1e2e7][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#587539,fg=#f0f0f0,bold] #I:#W #[default]'
