# github-dark tmux colors
set -g pane-border-style fg=#6e7681
set -g pane-active-border-style fg=#56d364
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#a0a7ae,fg=#0d1117'
set -g status-left '#[fg=#0d1117,bold]#S #[fg=#483a1a]|'
set -g status-right '#[fg=#183e45]%Y-%m-%d #[fg=#0d1117,bold]%H:%M #[fg=#483a1a][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#56d364,fg=#0d1117,bold] #I:#W #[default]'
