# solarized-dark tmux colors
set -g pane-border-style fg=#586e75
set -g pane-active-border-style fg=#d33682
set -g status-bg '#002b36'
set -g status-fg '#839496'
set -g status-left '#[fg=#2aa198]#S #[fg=#b58900]|'
set -g status-right '#[fg=#2aa198]%Y-%m-%d #[fg=#839496]%H:%M #[fg=#b58900][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#eee8d5,bold]#I:#W#[default]'
