# carbonfox hypr/hyprlock colors.
$rosewater = rgb(dfdfe0)
$rosewaterAlpha = dfdfe0
$flamingo = rgb(dfdfe0)
$flamingoAlpha = dfdfe0
$pink = rgb(c8a5ff)
$pinkAlpha = c8a5ff
$mauve = rgb(be95ff)
$mauveAlpha = be95ff
$red = rgb(ee5396)
$redAlpha = ee5396
$maroon = rgb(f16da6)
$maroonAlpha = f16da6
$peach = rgb(3fc7c5)
$peachAlpha = 3fc7c5
$yellow = rgb(08bdba)
$yellowAlpha = 08bdba
$green = rgb(25be6a)
$greenAlpha = 25be6a
$teal = rgb(33b1ff)
$tealAlpha = 33b1ff
$sky = rgb(33b1ff)
$skyAlpha = 33b1ff
$sapphire = rgb(78a9ff)
$sapphireAlpha = 78a9ff
$blue = rgb(78a9ff)
$blueAlpha = 78a9ff
$lavender = rgb(8cb6ff)
$lavenderAlpha = 8cb6ff
$text = rgb(f2f4f8)
$textAlpha = f2f4f8
$subtext1 = rgb(dfdfe0)
$subtext1Alpha = dfdfe0
$subtext0 = rgb(dfdfe0)
$subtext0Alpha = dfdfe0
$overlay2 = rgb(484848)
$overlay2Alpha = 484848
$overlay1 = rgb(484848)
$overlay1Alpha = 484848
$overlay0 = rgb(484848)
$overlay0Alpha = 484848
$surface2 = rgb(484848)
$surface2Alpha = 484848
$surface1 = rgb(282828)
$surface1Alpha = 282828
$surface0 = rgb(282828)
$surface0Alpha = 282828
$base = rgb(161616)
$baseAlpha = 161616
$mantle = rgb(161616)
$mantleAlpha = 161616
$crust = rgb(161616)
$crustAlpha = 161616

$active_border = rgba(be95ffee) rgba(78a9ffee) 45deg
$inactive_border = rgba(484848aa)
$shadow_color = rgba(161616ee)
