# solarized-light tmux colors
set -g pane-border-style fg=#586e75
set -g pane-active-border-style fg=#268bd2
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#6d8289,fg=#141414'
set -g status-left '#[fg=#141414,bold]#S #[fg=#141414]|'
set -g status-right '#[fg=#141414]%Y-%m-%d #[fg=#141414,bold]%H:%M #[fg=#141414][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#268bd2,fg=#141414,bold] #I:#W #[default]'
