# melange tmux colors
set -g pane-border-style fg=#867462
set -g pane-active-border-style fg=#78997a
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#c1b8af,fg=#292522'
set -g status-left '#[fg=#292522,bold]#S #[fg=#504431]|'
set -g status-right '#[fg=#41463b]%Y-%m-%d #[fg=#292522,bold]%H:%M #[fg=#504431][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#78997a,fg=#292522,bold] #I:#W #[default]'
