# melange tmux colors
set -g pane-border-style fg=#867462
set -g pane-active-border-style fg=#b380b0
set -g status-bg '#292522'
set -g status-fg '#ece1d7'
set -g status-left '#[fg=#87a987]#S #[fg=#ebc06d]|'
set -g status-right '#[fg=#87a987]%Y-%m-%d #[fg=#ece1d7]%H:%M #[fg=#ebc06d][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#c1a78e,bold]#I:#W#[default]'
