# ayu-dark tmux colors
set -g pane-border-style fg=#686868
set -g pane-active-border-style fg=#fae994
set -g status-bg '#304357'
set -g status-fg '#b3b1ad'
set -g status-left '#[fg=#90e1c6]#S #[fg=#f9af4f]|'
set -g status-right '#[fg=#90e1c6]%Y-%m-%d #[fg=#b3b1ad]%H:%M #[fg=#f9af4f][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#c7c7c7,bold]#I:#W#[default]'
