# tokyonight-moon hypr/hyprlock colors.
$rosewater = rgb(828bb8)
$rosewaterAlpha = 828bb8
$flamingo = rgb(828bb8)
$flamingoAlpha = 828bb8
$pink = rgb(c099ff)
$pinkAlpha = c099ff
$mauve = rgb(c099ff)
$mauveAlpha = c099ff
$red = rgb(ff757f)
$redAlpha = ff757f
$maroon = rgb(ff757f)
$maroonAlpha = ff757f
$peach = rgb(ffc777)
$peachAlpha = ffc777
$yellow = rgb(ffc777)
$yellowAlpha = ffc777
$green = rgb(c3e88d)
$greenAlpha = c3e88d
$teal = rgb(86e1fc)
$tealAlpha = 86e1fc
$sky = rgb(86e1fc)
$skyAlpha = 86e1fc
$sapphire = rgb(82aaff)
$sapphireAlpha = 82aaff
$blue = rgb(82aaff)
$blueAlpha = 82aaff
$lavender = rgb(82aaff)
$lavenderAlpha = 82aaff
$text = rgb(c8d3f5)
$textAlpha = c8d3f5
$subtext1 = rgb(828bb8)
$subtext1Alpha = 828bb8
$subtext0 = rgb(828bb8)
$subtext0Alpha = 828bb8
$overlay2 = rgb(444a73)
$overlay2Alpha = 444a73
$overlay1 = rgb(444a73)
$overlay1Alpha = 444a73
$overlay0 = rgb(444a73)
$overlay0Alpha = 444a73
$surface2 = rgb(444a73)
$surface2Alpha = 444a73
$surface1 = rgb(1b1d2b)
$surface1Alpha = 1b1d2b
$surface0 = rgb(1b1d2b)
$surface0Alpha = 1b1d2b
$base = rgb(222436)
$baseAlpha = 222436
$mantle = rgb(222436)
$mantleAlpha = 222436
$crust = rgb(222436)
$crustAlpha = 222436

$active_border = rgba(c099ffee) rgba(82aaffee) 45deg
$inactive_border = rgba(444a73aa)
$shadow_color = rgba(222436ee)
