# github-light hypr/hyprlock colors.
$rosewater = rgb(6e7781)
$rosewaterAlpha = 6e7781
$flamingo = rgb(6e7781)
$flamingoAlpha = 6e7781
$pink = rgb(a475f9)
$pinkAlpha = a475f9
$mauve = rgb(8250df)
$mauveAlpha = 8250df
$red = rgb(cf222e)
$redAlpha = cf222e
$maroon = rgb(a40e26)
$maroonAlpha = a40e26
$peach = rgb(633c01)
$peachAlpha = 633c01
$yellow = rgb(4d2d00)
$yellowAlpha = 4d2d00
$green = rgb(116329)
$greenAlpha = 116329
$teal = rgb(1b7c83)
$tealAlpha = 1b7c83
$sky = rgb(1b7c83)
$skyAlpha = 1b7c83
$sapphire = rgb(0969da)
$sapphireAlpha = 0969da
$blue = rgb(0969da)
$blueAlpha = 0969da
$lavender = rgb(218bff)
$lavenderAlpha = 218bff
$text = rgb(24292f)
$textAlpha = 24292f
$subtext1 = rgb(6e7781)
$subtext1Alpha = 6e7781
$subtext0 = rgb(6e7781)
$subtext0Alpha = 6e7781
$overlay2 = rgb(57606a)
$overlay2Alpha = 57606a
$overlay1 = rgb(57606a)
$overlay1Alpha = 57606a
$overlay0 = rgb(57606a)
$overlay0Alpha = 57606a
$surface2 = rgb(57606a)
$surface2Alpha = 57606a
$surface1 = rgb(24292f)
$surface1Alpha = 24292f
$surface0 = rgb(24292f)
$surface0Alpha = 24292f
$base = rgb(ffffff)
$baseAlpha = ffffff
$mantle = rgb(ffffff)
$mantleAlpha = ffffff
$crust = rgb(ffffff)
$crustAlpha = ffffff

$active_border = rgba(8250dfee) rgba(0969daee) 45deg
$inactive_border = rgba(57606aaa)
$shadow_color = rgba(ffffffee)
