# oxocarbon tmux colors
set -g pane-border-style fg=#525252
set -g pane-active-border-style fg=#42be65
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#c2c3c6,fg=#161616'
set -g status-left '#[fg=#161616,bold]#S #[fg=#594973]|'
set -g status-right '#[fg=#225151]%Y-%m-%d #[fg=#161616,bold]%H:%M #[fg=#594973][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#42be65,fg=#161616,bold] #I:#W #[default]'
