# oxocarbon tmux colors
set -g pane-border-style fg=#525252
set -g pane-active-border-style fg=#ee5396
set -g status-bg '#161616'
set -g status-fg '#f2f4f8'
set -g status-left '#[fg=#3ddbd9]#S #[fg=#be95ff]|'
set -g status-right '#[fg=#3ddbd9]%Y-%m-%d #[fg=#f2f4f8]%H:%M #[fg=#be95ff][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#dde1e6,bold]#I:#W#[default]'
