# github-light tmux colors
set -g pane-border-style fg=#57606a
set -g pane-active-border-style fg=#0969da
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#54585d,fg=#ffffff'
set -g status-left '#[fg=#ffffff,bold]#S #[fg=#dbd5cc]|'
set -g status-right '#[fg=#bbd8da]%Y-%m-%d #[fg=#ffffff,bold]%H:%M #[fg=#dbd5cc][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#0969da,fg=#ffffff,bold] #I:#W #[default]'
