# terafox hypr/hyprlock colors.
$rosewater = rgb(eaeeee)
$rosewaterAlpha = eaeeee
$flamingo = rgb(eaeeee)
$flamingoAlpha = eaeeee
$pink = rgb(c78ba0)
$pinkAlpha = c78ba0
$mauve = rgb(ad5c7c)
$mauveAlpha = ad5c7c
$red = rgb(e85c51)
$redAlpha = e85c51
$maroon = rgb(eb746b)
$maroonAlpha = eb746b
$peach = rgb(ffa07a)
$peachAlpha = ffa07a
$yellow = rgb(fda47f)
$yellowAlpha = fda47f
$green = rgb(7aa4a1)
$greenAlpha = 7aa4a1
$teal = rgb(a1cdd8)
$tealAlpha = a1cdd8
$sky = rgb(a1cdd8)
$skyAlpha = a1cdd8
$sapphire = rgb(5a93aa)
$sapphireAlpha = 5a93aa
$blue = rgb(5a93aa)
$blueAlpha = 5a93aa
$lavender = rgb(73a3b7)
$lavenderAlpha = 73a3b7
$text = rgb(e6eaea)
$textAlpha = e6eaea
$subtext1 = rgb(eaeeee)
$subtext1Alpha = eaeeee
$subtext0 = rgb(eaeeee)
$subtext0Alpha = eaeeee
$overlay2 = rgb(4e5157)
$overlay2Alpha = 4e5157
$overlay1 = rgb(4e5157)
$overlay1Alpha = 4e5157
$overlay0 = rgb(4e5157)
$overlay0Alpha = 4e5157
$surface2 = rgb(4e5157)
$surface2Alpha = 4e5157
$surface1 = rgb(2f3239)
$surface1Alpha = 2f3239
$surface0 = rgb(2f3239)
$surface0Alpha = 2f3239
$base = rgb(152528)
$baseAlpha = 152528
$mantle = rgb(152528)
$mantleAlpha = 152528
$crust = rgb(152528)
$crustAlpha = 152528

$active_border = rgba(ad5c7cee) rgba(5a93aaee) 45deg
$inactive_border = rgba(4e5157aa)
$shadow_color = rgba(152528ee)
