# material tmux colors
set -g pane-border-style fg=#546e7a
set -g pane-active-border-style fg=#c792ea
set -g status-bg '#263238'
set -g status-fg '#eeffff'
set -g status-left '#[fg=#89ddff]#S #[fg=#ffcb6b]|'
set -g status-right '#[fg=#89ddff]%Y-%m-%d #[fg=#eeffff]%H:%M #[fg=#ffcb6b][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[fg=#eeffff,bold]#I:#W#[default]'
