# material tmux colors
set -g pane-border-style fg=#546e7a
set -g pane-active-border-style fg=#82aaff
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#c2d2d3,fg=#263238'
set -g status-left '#[fg=#263238,bold]#S #[fg=#5c5845]|'
set -g status-right '#[fg=#3f5d6a]%Y-%m-%d #[fg=#263238,bold]%H:%M #[fg=#5c5845][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#82aaff,fg=#263238,bold] #I:#W #[default]'
