# dracula tmux colors
set -g pane-border-style fg=#6272a4
set -g pane-active-border-style fg=#ff79c6
set -gu status-bg
set -gu status-fg
set -g status-style 'bg=#ff79c6,fg=#21222c'
set -g status-left '#[fg=#21222c,bold]#S #[fg=#21222c]|'
set -g status-right '#[fg=#21222c]%Y-%m-%d #[fg=#21222c,bold]%H:%M #[fg=#21222c][#(whoami)]'
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#[bg=#282a36,fg=#8be9fd,bold] #I:#W #[default]'
