# monokai hypr/hyprlock colors.
$rosewater = rgb(f8f8f2)
$rosewaterAlpha = f8f8f2
$flamingo = rgb(f8f8f2)
$flamingoAlpha = f8f8f2
$pink = rgb(ae81ff)
$pinkAlpha = ae81ff
$mauve = rgb(ae81ff)
$mauveAlpha = ae81ff
$red = rgb(f92672)
$redAlpha = f92672
$maroon = rgb(f92672)
$maroonAlpha = f92672
$peach = rgb(f4bf75)
$peachAlpha = f4bf75
$yellow = rgb(f4bf75)
$yellowAlpha = f4bf75
$green = rgb(a6e22e)
$greenAlpha = a6e22e
$teal = rgb(a1efe4)
$tealAlpha = a1efe4
$sky = rgb(a1efe4)
$skyAlpha = a1efe4
$sapphire = rgb(66d9ef)
$sapphireAlpha = 66d9ef
$blue = rgb(66d9ef)
$blueAlpha = 66d9ef
$lavender = rgb(66d9ef)
$lavenderAlpha = 66d9ef
$text = rgb(f8f8f2)
$textAlpha = f8f8f2
$subtext1 = rgb(f8f8f2)
$subtext1Alpha = f8f8f2
$subtext0 = rgb(f8f8f2)
$subtext0Alpha = f8f8f2
$overlay2 = rgb(75715e)
$overlay2Alpha = 75715e
$overlay1 = rgb(75715e)
$overlay1Alpha = 75715e
$overlay0 = rgb(75715e)
$overlay0Alpha = 75715e
$surface2 = rgb(75715e)
$surface2Alpha = 75715e
$surface1 = rgb(272822)
$surface1Alpha = 272822
$surface0 = rgb(272822)
$surface0Alpha = 272822
$base = rgb(272822)
$baseAlpha = 272822
$mantle = rgb(272822)
$mantleAlpha = 272822
$crust = rgb(272822)
$crustAlpha = 272822

$active_border = rgba(ae81ffee) rgba(66d9efee) 45deg
$inactive_border = rgba(75715eaa)
$shadow_color = rgba(272822ee)
