# github-dark hypr/hyprlock colors.
$rosewater = rgb(b1bac4)
$rosewaterAlpha = b1bac4
$flamingo = rgb(b1bac4)
$flamingoAlpha = b1bac4
$pink = rgb(d2a8ff)
$pinkAlpha = d2a8ff
$mauve = rgb(bc8cff)
$mauveAlpha = bc8cff
$red = rgb(ff7b72)
$redAlpha = ff7b72
$maroon = rgb(ffa198)
$maroonAlpha = ffa198
$peach = rgb(e3b341)
$peachAlpha = e3b341
$yellow = rgb(d29922)
$yellowAlpha = d29922
$green = rgb(3fb950)
$greenAlpha = 3fb950
$teal = rgb(39c5cf)
$tealAlpha = 39c5cf
$sky = rgb(39c5cf)
$skyAlpha = 39c5cf
$sapphire = rgb(58a6ff)
$sapphireAlpha = 58a6ff
$blue = rgb(58a6ff)
$blueAlpha = 58a6ff
$lavender = rgb(79c0ff)
$lavenderAlpha = 79c0ff
$text = rgb(c9d1d9)
$textAlpha = c9d1d9
$subtext1 = rgb(b1bac4)
$subtext1Alpha = b1bac4
$subtext0 = rgb(b1bac4)
$subtext0Alpha = b1bac4
$overlay2 = rgb(6e7681)
$overlay2Alpha = 6e7681
$overlay1 = rgb(6e7681)
$overlay1Alpha = 6e7681
$overlay0 = rgb(6e7681)
$overlay0Alpha = 6e7681
$surface2 = rgb(6e7681)
$surface2Alpha = 6e7681
$surface1 = rgb(484f58)
$surface1Alpha = 484f58
$surface0 = rgb(484f58)
$surface0Alpha = 484f58
$base = rgb(0d1117)
$baseAlpha = 0d1117
$mantle = rgb(0d1117)
$mantleAlpha = 0d1117
$crust = rgb(0d1117)
$crustAlpha = 0d1117

$active_border = rgba(bc8cffee) rgba(58a6ffee) 45deg
$inactive_border = rgba(6e7681aa)
$shadow_color = rgba(0d1117ee)
