name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          Changes in this release:
          
          - Please update this text with release notes
          
          ## Installation Options
          
          ### Option 1: Install dotfiles utility (recommended)
          
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})
          make install    # Install the dotfiles utility
          dotfiles install  # Set up the dotfiles
          ```
          
          Or in one step:
          
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})
          make setup
          ```
          
          ### Option 2: Legacy installation
          
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})
          ./install.sh
          ```
