name: Test Dotfiles

on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install ShellCheck
      run: sudo apt update && sudo apt install -y shellcheck
    
    - name: Run linting
      run: ./lint.sh

  test:
    name: Test
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y stow
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install stow
    
    - name: Debug environment
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "Current directory: $(pwd)"
        echo "Git version: $(git --version)"
        ls -la
    
    - name: Install BATS
      run: |
        chmod +x tests/install_bats.sh
        ./tests/install_bats.sh
        ls -la tests/lib/bats-core/bin
    
    - name: Run tests
      run: |
        chmod +x test.sh
        ./test.sh
    
    - name: Test actual installation
      run: |
        # Create a test user home directory
        mkdir -p /tmp/home
        export HOME=/tmp/home
        
        # Run the install script
        ./install.sh
        
        # Verify symlinks were created
        echo "Checking created symlinks:"
        ls -la /tmp/home
        
        # Check that config directory was linked if it exists
        if [ -d "config/.config" ]; then
          echo "Checking .config directory:"
          ls -la /tmp/home/.config
        fi
        
        # Verify a few specific files
        for file in .bashrc .bash_aliases .profile .gitconfig; do
          if [ -f "config/$file" ]; then
            echo "Checking $file..."
            test -L "/tmp/home/$file" || (echo "$file symlink not created" && exit 1)
            echo "$file correctly linked"
          fi
        done
