name: Test Dotfiles

on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install ShellCheck
      run: sudo apt update && sudo apt install -y shellcheck
    
    - name: Run linting
      run: |
        # Only lint shell scripts, not BATS tests which require special handling
        echo "Linting shell scripts..."
        
        # Find shell scripts (excluding .bats files)
        SHELL_SCRIPTS=$(find . -type f -name "*.sh" | grep -v "tests/lib" | grep -v "^./.git/")
        
        # Find install script separately
        INSTALL_SCRIPT=$(find . -type f -name "install" -not -path "*/\.*")
        
        # Combine and lint
        echo "$SHELL_SCRIPTS $INSTALL_SCRIPT" | xargs shellcheck -x
        
        # Check bash configuration files
        if [ -f "config/.bashrc" ]; then
          echo "Checking config/.bashrc..."
          shellcheck -x config/.bashrc || true
        fi
        
        if [ -f "config/.bash_aliases" ]; then
          echo "Checking config/.bash_aliases..."
          shellcheck -x config/.bash_aliases || true
        fi
        
        if [ -f "config/.profile" ]; then
          echo "Checking config/.profile..."
          shellcheck -x config/.profile || true
        fi
        
        echo "Linting completed successfully!"

  test-standard:
    name: Test on Standard Platforms
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y stow
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install bash git stow bats-core 
        
        echo "Working directory"
        echo $(pwd)
        
        # Create lib directory for BATS helpers
        mkdir -p tests/lib
        
        # Install bats-support manually
        if [ ! -d "tests/lib/bats-support" ]; then
          echo "Installing bats-support..."
          git clone --depth 1 https://github.com/bats-core/bats-support.git tests/lib/bats-support
        fi
        
        # Install bats-assert manually
        if [ ! -d "tests/lib/bats-assert" ]; then
          echo "Installing bats-assert..."
          git clone --depth 1 https://github.com/bats-core/bats-assert.git tests/lib/bats-assert
        fi
    
    - name: Debug environment
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "Current directory: $(pwd)"
        echo "Git version: $(git --version)"
        ls -la
        if command -v bats &>/dev/null; then
          echo "System bats found: $(which bats)"
          bats --version
        else
          echo "System bats not found"
        fi
        
        # Check for BATS libraries
        echo "Checking for BATS libraries:"
        ls -la tests/lib || echo "No tests/lib directory found"
    
    - name: Install BATS
      run: |
        chmod +x tests/install_bats.sh
        ./tests/install_bats.sh
        
        # Show the bats installation
        echo "BATS installation:"
        ls -la tests/lib/bats-core || echo "bats-core not found"
        ls -la tests/lib/bats-support || echo "bats-support not found"
        ls -la tests/lib/bats-assert || echo "bats-assert not found"
        
        if [ -d "tests/lib/bats-core/bin" ]; then
          echo "BATS bin directory:"
          ls -la tests/lib/bats-core/bin
        fi
    
    - name: Run tests
      run: |
        chmod +x test.sh
        ./test.sh
    
    - name: Test actual installation
      run: |
        # Create a test user home directory
        mkdir -p /tmp/home
        export HOME=/tmp/home
        
        # Run the install script
        ./install.sh
        
        # Verify symlinks were created
        echo "Checking created symlinks:"
        ls -la /tmp/home
        
        # Check that config directory was linked if it exists
        if [ -d "config/.config" ]; then
          echo "Checking .config directory:"
          ls -la /tmp/home/.config
        fi
        
        # Verify a few specific files
        for file in .bashrc .bash_aliases .profile .gitconfig; do
          if [ -f "config/$file" ]; then
            echo "Checking $file..."
            test -L "/tmp/home/$file" || (echo "$file symlink not created" && exit 1)
            echo "$file correctly linked"
          fi
        done

  test-additional:
    name: Test on Additional Linux Distributions
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ['fedora:latest', 'archlinux:latest']
      fail-fast: false
    
    container:
      image: ${{ matrix.distro }}
    
    steps:
    - name: Install Git and other dependencies (Fedora)
      if: contains(matrix.distro, 'fedora')
      run: |
        dnf -y update
        dnf -y install git make stow findutils which procps-ng
        
        # Install BATS dependencies
        dnf -y install bats
    
    - name: Install Git and other dependencies (Arch Linux)
      if: contains(matrix.distro, 'archlinux')
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git make stow findutils which procps
        
        # Install BATS dependencies
        pacman -S --noconfirm bats
    
    - name: Set Git safe directory (pre-checkout)
      run: |
        # Configure Git to trust all directories
        git config --global --add safe.directory '*'
        git config --global --add safe.directory /__w/dotfiles/dotfiles
        
        # Verify Git configuration
        echo "Git configuration:"
        git config --list
    
    - name: Manual repository checkout
      run: |
        # Create directory for the repository
        mkdir -p /tmp/repo
        cd /tmp/repo
        
        # Clone the repository
        git clone https://github.com/${{ github.repository }} .
        
        # Checkout the specific ref
        git checkout ${{ github.sha }}
        
        # Show repository contents
        echo "Repository contents:"
        ls -la
        
        # Copy repository to the working directory
        cp -r . /__w/dotfiles/dotfiles/
        cd /__w/dotfiles/dotfiles/
        
        # Show working directory contents
        echo "Working directory contents:"
        ls -la
    
    - name: Debug environment
      run: |
        echo "Distro: ${{ matrix.distro }}"
        echo "Current directory: $(pwd)"
        echo "Git version: $(git --version)"
        ls -la
        if command -v bats &>/dev/null; then
          echo "System bats found: $(which bats)"
          bats --version
        else
          echo "System bats not found"
        fi
    
    - name: Install BATS
      run: |
        chmod +x tests/install_bats.sh
        ./tests/install_bats.sh
        
        # Show the bats installation
        echo "BATS installation:"
        ls -la tests/lib/bats-core || echo "bats-core not found"
        ls -la tests/lib/bats-support || echo "bats-support not found"
        ls -la tests/lib/bats-assert || echo "bats-assert not found"
    
    - name: Run tests
      run: |
        chmod +x test.sh
        ./test.sh
    
    - name: Test actual installation
      run: |
        # Create a test user home directory
        mkdir -p /tmp/home
        export HOME=/tmp/home
        
        # Create a simplified install script that doesn't use Git
        cat > install_container.sh << 'EOF'
        #!/bin/bash
        # Modified install script for container environments
        
        # Set default stow directory to current directory
        STOW_DIR="$(pwd)"
        
        # Create target directory if it doesn't exist
        mkdir -p "$HOME"
        
        # Run stow directly without Git checks
        echo "Running stow in container environment..."
        stow -v -t "$HOME" -d "$STOW_DIR" config
        
        # Exit with stow's exit code
        exit $?
        EOF
        
        # Make it executable
        chmod +x install_container.sh
        
        # Run the simplified install script
        ./install_container.sh
        
        # Verify symlinks were created
        echo "Checking created symlinks:"
        ls -la /tmp/home
        
        # Check that config directory was linked if it exists
        if [ -d "config/.config" ]; then
          echo "Checking .config directory:"
          ls -la /tmp/home/.config
        fi
        
        # Verify a few specific files
        for file in .bashrc .bash_aliases .profile .gitconfig; do
          if [ -f "config/$file" ]; then
            echo "Checking $file..."
            test -L "/tmp/home/$file" || (echo "$file symlink not created" && exit 1)
            echo "$file correctly linked"
          fi
        done
