# terafox kitty colors.
foreground              #e6eaea
background              #152528
selection_foreground    #e6eaea
selection_background    #4e5157
url_color               #5a93aa
color0  #2f3239
color1  #e85c51
color2  #7aa4a1
color3  #fda47f
color4  #5a93aa
color5  #ad5c7c
color6  #a1cdd8
color7  #eaeeee
color8  #4e5157
color9  #eb746b
color10 #8eb2af
color11 #ffa07a
color12 #73a3b7
color13 #c78ba0
color14 #afdfeb
color15 #fdf1ed
cursor                  #e6eaea
cursor_text_color       #152528
active_border_color     #ad5c7c
inactive_border_color   #4e5157
