# kanagawa-wave hypr/hyprlock colors.
$rosewater = rgb(c8c093)
$rosewaterAlpha = c8c093
$flamingo = rgb(c8c093)
$flamingoAlpha = c8c093
$pink = rgb(938aa9)
$pinkAlpha = 938aa9
$mauve = rgb(957fb8)
$mauveAlpha = 957fb8
$red = rgb(c34043)
$redAlpha = c34043
$maroon = rgb(e82424)
$maroonAlpha = e82424
$peach = rgb(e6c384)
$peachAlpha = e6c384
$yellow = rgb(c0a36e)
$yellowAlpha = c0a36e
$green = rgb(76946a)
$greenAlpha = 76946a
$teal = rgb(6a9589)
$tealAlpha = 6a9589
$sky = rgb(6a9589)
$skyAlpha = 6a9589
$sapphire = rgb(7e9cd8)
$sapphireAlpha = 7e9cd8
$blue = rgb(7e9cd8)
$blueAlpha = 7e9cd8
$lavender = rgb(7fb4ca)
$lavenderAlpha = 7fb4ca
$text = rgb(dcd7ba)
$textAlpha = dcd7ba
$subtext1 = rgb(c8c093)
$subtext1Alpha = c8c093
$subtext0 = rgb(c8c093)
$subtext0Alpha = c8c093
$overlay2 = rgb(727169)
$overlay2Alpha = 727169
$overlay1 = rgb(727169)
$overlay1Alpha = 727169
$overlay0 = rgb(727169)
$overlay0Alpha = 727169
$surface2 = rgb(727169)
$surface2Alpha = 727169
$surface1 = rgb(090618)
$surface1Alpha = 090618
$surface0 = rgb(090618)
$surface0Alpha = 090618
$base = rgb(1f1f28)
$baseAlpha = 1f1f28
$mantle = rgb(1f1f28)
$mantleAlpha = 1f1f28
$crust = rgb(1f1f28)
$crustAlpha = 1f1f28

$active_border = rgba(957fb8ee) rgba(7e9cd8ee) 45deg
$inactive_border = rgba(727169aa)
$shadow_color = rgba(1f1f28ee)
