# catppuccin-macchiato hypr/hyprlock colors.
$rosewater = rgb(b8c0e0)
$rosewaterAlpha = b8c0e0
$flamingo = rgb(b8c0e0)
$flamingoAlpha = b8c0e0
$pink = rgb(f5bde6)
$pinkAlpha = f5bde6
$mauve = rgb(f5bde6)
$mauveAlpha = f5bde6
$red = rgb(ed8796)
$redAlpha = ed8796
$maroon = rgb(ed8796)
$maroonAlpha = ed8796
$peach = rgb(eed49f)
$peachAlpha = eed49f
$yellow = rgb(eed49f)
$yellowAlpha = eed49f
$green = rgb(a6da95)
$greenAlpha = a6da95
$teal = rgb(8bd5ca)
$tealAlpha = 8bd5ca
$sky = rgb(8bd5ca)
$skyAlpha = 8bd5ca
$sapphire = rgb(8aadf4)
$sapphireAlpha = 8aadf4
$blue = rgb(8aadf4)
$blueAlpha = 8aadf4
$lavender = rgb(8aadf4)
$lavenderAlpha = 8aadf4
$text = rgb(cad3f5)
$textAlpha = cad3f5
$subtext1 = rgb(b8c0e0)
$subtext1Alpha = b8c0e0
$subtext0 = rgb(b8c0e0)
$subtext0Alpha = b8c0e0
$overlay2 = rgb(5b6078)
$overlay2Alpha = 5b6078
$overlay1 = rgb(5b6078)
$overlay1Alpha = 5b6078
$overlay0 = rgb(5b6078)
$overlay0Alpha = 5b6078
$surface2 = rgb(5b6078)
$surface2Alpha = 5b6078
$surface1 = rgb(494d64)
$surface1Alpha = 494d64
$surface0 = rgb(494d64)
$surface0Alpha = 494d64
$base = rgb(24273a)
$baseAlpha = 24273a
$mantle = rgb(24273a)
$mantleAlpha = 24273a
$crust = rgb(24273a)
$crustAlpha = 24273a

$active_border = rgba(f5bde6ee) rgba(8aadf4ee) 45deg
$inactive_border = rgba(5b6078aa)
$shadow_color = rgba(24273aee)
